### ISSUE TITLE
Concepts data intermittently changes?

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10150]
**What**
On Thursday 17th August, [e2es started failing in the `concepts.test.ts` file](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/3260#018a02af-2c04-4020-aaf1-66a50e3ab6de) ([see Slack conversation](https://wellcome.slack.com/archives/C02ANCYL90E/p1692262571556779)). These tests point at various concept pages, based on the fact that they _had_ both images by/about, or works by/about. Suddenly, it wasn't the case anymore. 

One of the test subjects ([Joanna Stephens](https://wellcomecollection.org/concepts/pg43g9hn)), chosen because "there are works both about and by this person", but no longer did (see page), was replaced that morning by [Florence Nightingale](https://wellcomecollection.org/concepts/gk2eca5r), who still had works BY and ABOUT her at the time, as proven by passing tests and the fact that I chose her as a replacement. Later that day, those tests failed again, Florence Nightingale no longer had two tabs in the Catalogue section. 

Same thing happened with [John the Baptist](https://wellcomecollection.org/concepts/ywavfdsc) (the tests used to look at its Image section, which doesn't show anymore) and [Charles Darwin](https://wellcomecollection.org/concepts/v3m7uhy9) ("Chosen because there are images both about and by this organisation").

@paul-butcher mentioned this could have to do with 
> [John, the Baptist, Saint](https://wellcomecollection.org/concepts/ywavfdsc) has no trailing ., but the corresponding subject in [mdwrgvd4](https://wellcomecollection.org/works/mdwrgvd4) does.  I believe this is a consequence of us standardising the  title of the Concept using the [authoritative source](https://id.loc.gov/authorities/names/n78095804.html), but not having done so yet in Works. The link is derived from the identifier, but the page content is still populated using full term matches on the label.

Another factor in this is that the tests had to be fixed one by one, so is there something wrong with the tests themselves, or is it that the data would change at the exact wrong moment? I would:

1. Fix the bugs (Joanna Stephens, replacing her with Florence Nightingale)
2. Run the e2es in the branch, all passed
3. Merge in main/staging
4. E2es failed in staging (for John the Baptist)
5. Fix John the Baptist
6. Run tests locally and in the branch, all pass
7. Merge in main/staging
8. E2es failed in staging (Charles Darwin)
9. Fix Darwin
6. Run tests locally and in the branch, all pass
7. Merge in main/staging
10. Everything passes, deploy to production.
11. Hours later, David merges a unrelated commit in main/staging
12. E2es fail (Florence Nightingale - no longer has tabs in the works section)

The fact that Florence Nightingale tests used to work earlier that same day makes me think something is up.

**Comment by rcantin-w** [comment]
It happens elsewhere as well: https://wellcome.slack.com/archives/C02ANCYL90E/p1692352152081469

**Comment by paul-butcher** [comment]
It looks like a bunch of records have had punctuation added to some fields recently.  (10th August),

e.g. in the Sierra document corresponding to https://wellcomecollection.org/works/v68gc9qg (b13084239), the contributor which is now "Bernard, de Gordon, approximately 1260-approximately 1318." was simply "Bernard, de Gordon, approximately 1260-approximately 1318" [on the 3rd of August](s3://wellcomecollection-vhs-sierra-sierra-adapter-20200604/1308423/19/524b69e0-65b3-48ab-b207-93c9568b69d1.json).  [The dot was added on the 10th](s3://wellcomecollection-vhs-sierra-sierra-adapter-20200604/1308423/20/fa795e9d-23bb-4773-9af3-b8faf78b0e43.json)


The same is true of [this picture of Charles Darwin](https://www.wellcomecollection.org/works/uts9a9q4). [Since 2023-08-10 there has been a dot after 1882](s3://wellcomecollection-vhs-sierra-sierra-adapter-20200604/1163576/20/fbc4438e-f451-4838-8e22-ffff39494bc6.json), [but on 2023-08-03, there was no dot](s3://wellcomecollection-vhs-sierra-sierra-adapter-20200604/1163576/19/a321114b-3f88-4d9d-adf5-018c5778118d.json)

There are two places for this to be resolved.  

It is (I believe) correct that the punctuation present in these source documents should be displayed on the web pages, so the e2e test "Scenario 3: A user wants information about the item they are viewing › the item has contributor information" that is [failing because of a difference in punctuation](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/3273#018a0806-353a-48eb-b95c-05e8f85f05c4/281-342) should be changed to either be more tolerant, or to actually expect the punctuation.

However, I do not believe it is correct for trailing full stops (at least, and probably other punctuation) to cause the API to return two different sets of results when filtering on

 "Darwin, Charles, 1809-1882" vs "Darwin, Charles, 1809-1882.".  Nor should an entry appear twice in the filtering dropdown, differing only on a trailing `.`.

![Screenshot 2023-08-21 at 14 18 28](https://github.com/wellcomecollection/wellcomecollection.org/assets/64621/51a53dec-60b9-4082-83e1-8d95c8d5537b)

So I think the value should be trimmed of this punctuation (at least trailing stops) before being used to populate the query and aggregable fields.

**Comment by paul-butcher** [comment]
I don't know why the Darwin with the trailing dot seemed to have worked last year according to archive.org.  I don't recall any changes that would make the filters more sensitive to trailing punctuation.

**Comment by paul-butcher** [comment]
Florence Nightingale is the same. [greetings to the dear old comrades of Balaclava](https://wellcomecollection.org/works/e6x2ykzq) had no trailing dot on the 4th, and on the 17th, it gained one.

**Comment by rcantin-w** [comment]
Covered by https://github.com/wellcomecollection/catalogue-pipeline/issues/2436 and https://github.com/wellcomecollection/catalogue-pipeline/issues/2424
