### ISSUE TITLE
Hint text for form fields/Refactor Input Text component

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#10234]
**What**
Placeholder text disappears when a form field is navigated to. Users need additional cues / hint text whilst filling in a form field.

**Where**
Form fields

**TODO**

- [ ] Provide additional cues / hint text that persists whilst filling in a form field
- [ ] Add pattern to Cardigan

**Background**

From the Hassell Inclusion accessibility audit August 2023.

Dovetail: https://proficient-wallaby-dpwd.dovetailapp.com/insights/Need-additional-cues-for-entering-information-in-form-fields-MjtohTWntPJtuP7J1y1YJ

Miro board: https://miro.com/app/board/uXjVMjsL5YE=/

**Comment by j-jaworski** [comment]
Designs for this ticket are covered in #10269 Exploration around search filters behaviour when you get to the end of a filter

**Comment by j-jaworski** [comment]
I think we have 2 options here

1. Use the form elements developed and defined for Wellcome FRP (Funding Relationship Platform product) and have been used across many of the other products at Wellcome.

**Designs in Figma**
https://www.figma.com/file/6bg5Y3Y4gLXgSdVa8Da8Vy/Wellcome-design-system?type=design&node-id=1429%3A5466&mode=dev&t=ALVqWmijUaT4oAZA-1

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/970cb92e-4ae1-46d8-9e88-e2a720fb25c2)


2. Use the UI that is used on this page across the whole site (although I can't point you towards designs for this option)
https://account.wellcomecollection.org/u/signup?state=hKFo2SAzRk1fLW1sb2hEZlo3dWRrcU1aR0xDRElXaDBlSl9Hb6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGxXLThmUlFqSXQ5WWZGZzZuOGxOT3dIeklfaU9zc01Zo2NpZNkgT3lGdjJIS0E0a1E2d2lDYjFXMDU5S1NMdVg5Z1V6cWg


![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/5756060e-399c-48bf-9e3f-b603313ec341)

**Comment by davidpmccormick** [comment]
Option ii. is similar to what we'd previously built ourselves, but I think we reverted to a more traditional (closer to option i.) approach for simplicity a while ago. The example in the link above is actually an Auth0 hosted page, so not an input we have control over.

I think given we moved away from option ii. the obvious route for us to take is to fill out what we already have in line with option i.

**Comment by rcantin-w** [comment]
AFAIK it's only the search bar (which is displayed in an array of pages but always with the same component) and the newsletter pages (the block at the bottom of pages and the one on `/newsletter`.

**Comment by j-jaworski** [comment]
Lots in this and trying to unpack it all and make sense, apologies if I have misunderstood or missed something.

My thoughts:
- Update form inputs to align with the UI with the FRP (either all together in one ticket or just the hint text field for now, however, you want to split the work)
- Keep the current validation error messaging for emails
- Add hint text message that guides the user 
- Where possible remove duplication in the UX copy, specifically between the label and hint text


**I have added designs for this pattern to this Figma file** 
https://www.figma.com/file/juZQR2wi2BsYG8TDH6R4uk/Wellcome-Collection-%E2%80%93-Styles-and-Component-Library-2023?type=design&node-id=1776%3A4028&mode=dev&t=Cu6Gm9mlde1dQRlV-1


 **Here are some screenshots for reference**


![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/b80b276b-4d7d-4ca3-a83c-496a0342f161)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/e9f7c217-494c-4ac5-8071-c7edb0b7233d)

**Comment by rcantin-w** [comment]
Ahh I'm sorry, I'm throwing a few more inputs in the mix.

Dates filter:
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/d996c59f-b800-4f64-aea7-4eac9edbcea3)


Pagination:
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/c8fc43a9-96e5-4608-9213-1b8a838d3919)
tbh this one is pretty self explanatory and is never empty.


Identity info changes:
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/55f1afe3-f468-4fc6-bf6b-83802533998d)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/8202a5c1-df12-4f31-94ca-78410274f687)

These are interesting because they are different from the other two styles, I think it might be a leftover from the fact that (I think?) an agency built Identity (I think?)

Anyway, they can be aligned to. I'm unsure about the Date filter bit though? They are a separate component called "NumberInput" versus the others which are "TextInput".

**Comment by rcantin-w** [comment]
Changes are in prod
