### ISSUE TITLE
Cookies banner button order

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10887]
Button order doesn't match designs in the new cookies banner.

Should be:
Manage cookies, Essential only, Accept all

Currently showing in reverse order behind toggle:
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/160641757/a7db25aa-897c-487b-aa92-40fc7c987215)

**Comment by rcantin-w** [comment]
We can't change it, sadly, only change the copy

**Comment by LaurenFBaily** [comment]
Thanks for the background.

Not a blocker for releasing, but need to look now that we're inconsistent with wellcome.org banner and whether that's a potential issue for users moving between the sites.

**Comment by rcantin-w** [comment]
Right, with access to their codebase, I can confirm why it is different; their solution includes having a custom-built banner. The initial state of Civic UK is `closed`, and instead of using what CivicUK offers like we do, they display a custom banner, meaning they have much more control over the look, copy, etc. and therefore can control the button order. 
So we could do the same down the line, if that's something we want.
Or we can look at adding extra CSS of top on the Civic UK solution, but we chose not to do that in case they changed their code and the CSS didn't apply anymore; more to maintain.

**Comment by LaurenFBaily** [comment]
Will pick up with wellcome.org team to see if they can instead align with our button ordering instead (having our preferred option 'Accept all' ordered first).

**Comment by LaurenFBaily** [comment]
Closing as wellcome.org are going to update their button order to match ours.
