### ISSUE TITLE
Ingested java script is not showing on the works page

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#11022]
## What

A java script that is ingested is not showing on the works page
![SACERC7](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/832c1a71-e6c2-4b13-b3bf-04a64e3de652)

## Where

SA/CER/C/7
https://wellcomecollection.org/works/d2fp58qm

## To do
- Show the script on the works page so that it can be downloaded

From [Ashley](https://wellcomecloud-my.sharepoint.com/:w:/r/personal/a_ray_wellcome_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B9FD07BCD-AF43-4324-B4F5-2DF5709E7C99%7D&file=born%20digital%20access%20issues.docx&wdLOR=cD50E2D01-E58F-4B8A-B88F-5E1A8954A38C&action=default&mobileredirect=true)

**Comment by gestchild** [comment]
I've spoken to Ashleigh, she's going to raise it with Digirati

**Comment by gestchild** [comment]
"So I had another look at this after lunch and noticed it said that the access condition was missing for the global.js file which wasn't true, I could see it had open labeled in the dashboard so I just took a chance on updating the IIIF manifest to see if it'd update the global.js's status from missing to open and it seems to have worked :woman-shrugging: We had an error similar to this on another item last week where the item wasn't picking up changes through the delivery channels that Tom Crane fixed a bug for so I suspect that's why this update fixed it" - from Ashley
