### ISSUE TITLE
Digital Guides styles fixes (incl scroll behaviour)

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11126]
Ticket created to address comments in https://github.com/wellcomecollection/wellcomecollection.org/pull/11119 and allow us to merge the PR.

- Possible bug on scroll behaviour ([see comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/11119#issuecomment-2306619444)) to fix
- Is there a font-size adjustment still to do? ([see comment](https://github.com/wellcomecollection/wellcomecollection.org/pull/11119#pullrequestreview-2256713207))

**Comment by davidpmccormick** [comment]
I think there are still a few comments that concerned `guides/[id]/[type]` which I didn't address (I only picked up the comments for the mess I'd created myself in `guide/[id]/[type]/[stop]`). I'll pick off the remaining ones. The scroll bug is a head-scratcher because the header is `position: sticky; top: 0;` (none of which is dynamically set) so it shouldn't scroll at all. I think this might need testing on real devices to validate – I'm currently hoping it is a bug with Chrome's mobile emulation

**Comment by davidpmccormick** [comment]
- Text size fixed in #11130 
- We're working on the assumption the scroll bug @rcantin-w found is peculiar to the Chrome mobile emulator since we don't see it on our _real_ iPhone/Android devices
