### ISSUE TITLE
Use Vimeo on Highlight Tours

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11408]
Youtube has started to block certain people from viewing the BSL videos, thinking they might be bots.
We're looking at alternative solutions.
[See Slack thread.](https://wellcome.slack.com/archives/CUA669WHH/p1731682148198029)

## To do
- [x] Amend Highlight tours video to allow for Vimeo videos
- [x] Does anything need doing analytics side? 
- [x] Vimeo to be added to cookie policy?

**Comment by pollecuttn** [comment]
https://wellcomecollection.org/guides/exhibitions/jason-and-the-adventure-of-254/bsl

https://wellcomecollection.org/guides/exhibitions/hard-graft/bsl

**Comment by LaurenFBaily** [comment]
This is the [cookie list ](https://help.vimeo.com/hc/en-us/articles/26080940921361-Vimeo-Player-Cookies) with the specified essential cookies.

**Comment by rcantin-w** [comment]
From a very quick read, it seems we could add `dnt=1` to the `iframe`'s src parameter, which we could do after checking whether or not the user has given consent. I'll have a try.

**Comment by rcantin-w** [comment]
By the way I'm just noticing we are adding the `dnt=true` by default at the moment so we won't be tracking people without their wanting to should we add Vimeos now.

I'm trying to remove it and see which cookies come up but nothing so far 🤔

**Comment by rcantin-w** [comment]
Can confirm it seems to work as expected and the integration is simple.

Now just need the Cookies policy page updates and whatever we think is good to add to this block in the Manager popup:
![Image](https://github.com/user-attachments/assets/6155176c-6cd4-438f-a513-f59892834ba3)

**Comment by LaurenFBaily** [comment]
To be added to the cookie policy page in the Analytics section:

Vimeo

We embed videos on our websites from our official Vimeo channel. With permission we collect data on how you interact with these videos. This information helps us improve the digital content we create. [Visit Vimeo to see a full list of cookies and their uses](https://help.vimeo.com/hc/en-us/articles/26080940921361-Vimeo-Player-Cookies)

I don't have a link for the opt out pop-up because the privacy page and cookie policy page on Vimeo website appear to be broken...

**Comment by LaurenFBaily** [comment]
Just to record this somewhere, addition of these cookies and the text above has been approved by Legal today as part of the new (accelerated) cookie procedure.

**Comment by rcantin-w** [comment]
The changes to consent and Cookie policies have been deployed to production.
