### ISSUE TITLE
Verify the behaviour of opening times in advance of the Christmas/New Year closure

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#11410]
Closure date for Christmas/New Year 2024-25 are now up on the site at https://wellcomecollection.org/visit-us/opening-times.

The library will closed at the end of the day on Friday 20 December 2024 and re-open on Thursday 2 January 2025.

We should do this by w/c 2 December in case anything needs fixing before two weeks before closure on 20 December.

Previous tickets e.g. https://github.com/wellcomecollection/wellcomecollection.org/issues/8976 show how we've tested requesting for previous closures.

There is also some info at https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/DPDDj27NI2F2kPukWrC1/end-of-year-closure

NB The Platform team are checking with LE&E re Deepstore orders now that those can be ordered online. This ticket still needs to go ahead in the meantime.

# To do
- Check requesting will behave as expected over the closure period

**Comment by agnesgaroux** [comment]
weco.org doesn't generate the available dates for requesting anymore so the above process https://github.com/wellcomecollection/wellcomecollection.org/issues/8976 will not work

**Comment by agnesgaroux** [comment]
The content-api `/venue` route provides the catalogue-api with opening times/available dates for requesting 
It can easily be run locally, and uses the same index that the live APIs use (so, same data, same dates)
Running the content-api locally, we can set whatever date we want to test [here](https://github.com/wellcomecollection/content-api/blob/44250f5182bc0ef00ba4a47979ed285d152b6cb7/api/src/controllers/utils.ts#L17), then 
- library
Hit `http://localhost:3000/venues?title=library%2Cdeepstore` will return a list of `nextOpeningDates` for both venues

**Comment by rcantin-w** [comment]
As per our chat just now with @agnesgaroux and @pollecuttn 

There are now two things to test, Agnès is currently re-writing the Github document to inform that.

- [ ] Test what happens for closed stores in-building (same testing as usual)
- [ ] Test what happens for Deepstore material. 

For the latter, Agnès is meeting with LE&E on Wednesday to determine what is expected to happen, then we can catch up again and see how Experience can assist.

As this now sits on Prismic/Content API AND Catalogue API logic, it might be that this is a joint effort from both teams for 30mins every December.

**Comment by rcantin-w** [comment]
[Test chats happening on Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1733145315469959)

**Comment by rcantin-w** [comment]
So I'm unsure how to test this properly without good knowledge of the logic done elsewhere (maybe on the Catalogue API?), which _I think_ affects which dates come through?

Test done so far;
- [Changed the date in the Content API](https://github.com/wellcomecollection/content-api/blob/main/api/src/controllers/utils.ts#L17) to pretend we're in Christmas closures. 
- Run Content API locally (`cd api && yarn dev` whilst logged on to AWS with the catalogue-developer role)
- Go to http://localhost:3000/venues?title=library
- See: `results.nextOpeningDates`

So far, when it's on an exceptional working day (let's say I change my date to be `2024-12-23T14:30:00.000Z`), I see that day be the first result in the `nextOpeningDates` array:

```
{
"open": "2024-12-23T10:00:00.000Z",
"close": "2024-12-23T18:00:00.000Z"
},
{
"open": "2025-01-02T10:00:00.000Z",
"close": "2025-01-02T20:00:00.000Z"
},
{
"open": "2025-01-03T10:00:00.000Z",
"close": "2025-01-03T18:00:00.000Z"
},
{
"open": "2025-01-04T10:00:00.000Z",
"close": "2025-01-04T16:00:00.000Z"
},
```
I believe this is because [this code removes it from "exceptional closing days"](https://github.com/wellcomecollection/content-api/blob/main/api/src/controllers/utils.ts#L27-L30) as it's considered to be in the past, even though it's on "day of". Therefore it shows as a nextOpeningDates, even though it probably shouldn't. I'm also not sure about the 2nd showing up, since that gives no time to our colleagues to fetch the work and make it available.

BUT, I believe there is code, probably in the Catalogue API, that removes those from the array, as "day of" will never be considered a valid option. When I inspect the WC.org code, [available dates seem to be fetched at this stage](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/PhysicalItems/PhysicalItems.tsx#L114). It is where I struggle to further my testing though, as I'm unsure of the spread of the logic, and do not know the Catalogue API. When I run it with today's date, it also returns today and tomorrow, but the first option on the FE is in two days. So I'm thinking it's probably fine, but don't feel comfortable confirming so.

I also feel like this test case makes me really want to be able to connect with local APIs easily for better testing 😄 something @kenoir and I touched on really quickly last week, one for a different time!
