### ISSUE TITLE
Works: Text display audit on Medium and Small breakpoints

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#4272]
Currently, the information is being wrapped making it difficult to scan. We should review the latest works on different breakpoints and recommend general rules for this type of information display. 

**Search Results**
![IMG_5134](https://user-images.githubusercontent.com/29206031/54463432-f8ee8f00-476a-11e9-9def-f56c90757f2a.png)

**Works Page**
![IMG_5135](https://user-images.githubusercontent.com/29206031/54463430-f8ee8f00-476a-11e9-8fa5-ca8944007606.png)

**Comment by GarethOrmerod** [comment]
This is captured on Zeplin by selecting the tags: Works Preview and BP Small.

The text is intended to wrap naturally and break so that Date starts on a new line .

<img width="1222" alt="Works preview BP small" src="https://user-images.githubusercontent.com/36885440/58642760-d72a9000-82f5-11e9-8b3d-cbba3ebf6eea.png">

**Comment by pollecuttn** [comment]
@jennpb With Gareth's Zeplin files linked above this is now ready for devs. I'll leave it with you for prioritizing.
