### ISSUE TITLE
Event card: displaying wrong date for multi date events in What's on

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#4522]
When an event with multiple dates is displayed on What's on, it's currently displaying the most recent upcoming date. Therefore, the event card under 'September' list displays July date and time.  Based on agreed display logic, it should display the earliest date for each month. 

Note: There's an enhancement request #2939 to remove event month filter and display a fixed set of events with the option to view more. Need to discuss whether to fix this bug or work on the enhancement.

What's on September listing
![Screen Shot 2019-06-12 at 11 27 47](https://user-images.githubusercontent.com/29206031/59344393-e81bce00-8d05-11e9-9c71-a8c48fbfaf7a.png)

Event detail with multiple dates
![Screen Shot 2019-06-12 at 11 28 00](https://user-images.githubusercontent.com/29206031/59344405-ef42dc00-8d05-11e9-9853-f81bd2c3374c.png)

**Comment by jamesgorrie** [comment]
@wellcometrust/experience-devs Similar to the way we're monkey patching `fetchLinks` and relationships - we've been monkey patching dates like crazy.

Would it feel more sustainable and scalable to start thinking about storing this information in another index to be able to return this business logic via and API rather than the rendering layer?

If we had that index these problems could be solved more abstractly and stop peeking up slowing down other development.
