### ISSUE TITLE
Rationalise all form and button elements

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4946]
Rationalise all form and button elements and create rules for them:
- buttons (primary, secondary, tertiary)
- default, hover and focus states

**Comment by pollecuttn** [comment]
5 March 2020: 
- carry on with looking at toggle for viewer, explore with labels e.g. icon only, expanded with label

**Comment by pollecuttn** [comment]
16 March 2020: collecting viewer improvement suggestions and putting into a presentable format - GO/DMa

**Comment by pollecuttn** [comment]
26 March 2020
- GO to package for zeplin and link to on this ticket
- GO/devs to get the form elements added to Cardigan

**Comment by GarethOrmerod** [comment]
Sketch artboards on Zeplin here:

zpl://project?tags=Form%20%26%20Buttons%20elements&pid=5aab926b4b6efde01259e959
https://zpl.io/V1nxDAQ

**Comment by davidpmccormick** [comment]
Something for discussion with @GarethOrmerod and @DominiqueMarshall 

I'm not sure what to do about focus states on links when they've been clicked rather than tabbed-to with the keyboard. Would you expect e.g. the main navigation links to receive the turquoise border styles from the [recent design updates](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e83717be237136cb70523ae) when they were clicked?

![image](https://user-images.githubusercontent.com/1394592/79584919-f590aa00-80c6-11ea-8b9e-e0bca4d3b95b.png)

We currently use a css reset that hides any `focus` style when you're hovering a link, but I'm experiencing some existential doubt about whether or not this is appropriate (and if not, it would re-open the debate about whether or not a button should retain its focused style after it has been clicked).

FWIW I see that e.g. gov.uk and southbankcentre.co.uk (who have implemented the kind of bold custom focus styles we're looking to go with) apply the focus style regardless of whether it's clicked on or keyboard-ed.

**Comment by GarethOrmerod** [comment]
Following up on discussing this with the team, the most appropriate direction would be for the focus state to be visible when tabbing using a keyboard but not always necessary when using mouse/trackpad. 

The design system should highlight an active state if it is needed without relying on :focus. e.g. tabbed navigation or accordions.

The instance where it is needed is within a form where highlighting the currently active form is beneficial.

**Comment by jamesgorrie** [comment]
@davidpmccormick do we know why an item is focussed when clicked? It feels like a deliberate choice by the browser devs and thus might have a use case?

**Comment by davidpmccormick** [comment]
I can imagine if you were to arrive on a page and focus was directed to a particular element, at that point the browser wouldn't have any knowledge of whether you were a mouse or keyboard user, so ensuring focus was visible to keyboard users would be the priority. If we default to this for server-rendered pages (by the addition of an initially-present `is-keyboard` class), then I think we're being good a11y citizens.

**Comment by davidpmccormick** [comment]
Closing as remaining button work is covered by #5230.
