### ISSUE TITLE
Test placement of Young People, Schools and Families pages within What's On

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4947]
# Problem to solve
After three rounds of tree testing for our navigation, we've learnt that the first-click for finding Youth, Schools and Families information is consistently in **What's On**, rather than the proposed `Get Involved` section, which was slated to replace `What We Do`.

- Is What's On the best place for this content?
- Is Get Involved the wrong label for this type of participatory programme?

I'd like to set up a test where we create a new section on What's On (following events list, but before the `Try these too` section) which includes cards for the Young People, Schools and Families pages.

I'd then like to monitor traffic from:

What's on -> Young People / Schools / Families
What we do -> Young People / Schools / Families

@taceybadgerbrook @wellcometrust/weco-experience-devs Could we spin up a test quickly?

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by taceybadgerbrook** [comment]
GA produces metrics on age if you select this (have just enabled this.)  Any analysis will just have to start from 29/2/20.

BUT

GA arrives at the age data by online travel and purchasing activities.  Under 18’s are not part of the age demographic report "for several reasons," most likely because these aren't the people who are doing the travelling and purchasing. So it won't be possible to identify behaviour.

GA's age categories are 18-24, 25-34, 35-44, 45-54, 55-64 & 65+.  There is no category for family but on Monday I can look to see whether the interests data might suggest proxy values.

**Comment by jennpb** [comment]
For the purposes of this test, I wouldn't need to know demographics of who's clicking on it. We don't get that information now. This test is rather about placement of links, rather than full behavioural analysis. Unless I'm missing part of your thinking here?

**Comment by taceybadgerbrook** [comment]
So it's not about seeing whether Youth/Schools/Families click on the link? Just whether the link is used?

**Comment by jennpb** [comment]
Precisely. Right now, you can only find it in `What we do`. I want to see what happens if it gets duplicated in  `What's on`.

My guess is that those pages will each get more traffic from What's On than they currently do in What We Do.
