### ISSUE TITLE
Tiny thumbnails on results after page refresh

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#4981]
**What**
Some results from some searches show teeny tiny thumbnails, not after the initial search but when I refresh the page, e.g.
https://wellcomecollection.org/works?query=quacks
https://wellcomecollection.org/works?query=botany
https://wellcomecollection.org/works?query=optics
I think I've only seen this on Books so far, but it doesn't affect all Books.

**Where**

From the [quacks](https://wellcomecollection.org/works?query=quacks) search

_After a page refresh_
![tiny](https://user-images.githubusercontent.com/1446072/72076241-235a9b80-32ed-11ea-9a56-80602051135f.PNG)

_What it's expected to look like_
![expected](https://user-images.githubusercontent.com/1446072/72076252-28b7e600-32ed-11ea-9685-e7038b8a41f5.PNG)

Tom Crane thinks it's a front end issue rather than an API issue:
"Yeah I noticed that but I think that's a front end issue, the thumb being displayed is still the 200 pixel one, just rendered very small."
[source](https://wellcome.slack.com/archives/CBT40CMKQ/p1578579997022200)

**Comment by jennpb** [comment]
We haven't included book thumbnails previously and I'm not sure we want to until we revisit the design of the work cards. Can we suppress these new additions until we look at this for real?

**Comment by davidpmccormick** [comment]
So only show thumbnails for `Digital Images` and `Pictures` (workTypes, 'q' and 'k') for now?

**Comment by jennpb** [comment]
Aye aye cap'n

**Comment by jamesgorrie** [comment]
@davidpmccormick the fix above doesn't fix this - the examples still stand and seems to be a frontend issue.

To replicate do the search and refresh in chrome.

**Comment by jamesgorrie** [comment]
We should probably remove the last fix as it doesn't solve anything and removes thumbnails from works that would otherwise have them.

**Comment by davidpmccormick** [comment]
Jenn [asked that thumbnails be removed from books for now](https://github.com/wellcometrust/wellcomecollection.org/issues/4981#issuecomment-572591768)

**Comment by alicefuzier** [comment]
Just a bit of context to debug this: the new index contains merged information coming from METS files. An example of such information is the URL of thumbnails in DLCS rather than Loris (ie iiif.wellcomecollection.org). Our rules say that wherever we have a thumbnail from DLCS instead of Loris we should choose DLCS. 
That is because thumbnails in DLCS are either better quality or rephotographed works whereas what we have in Loris is the old Miro images which tend to be worse quality. Also, as DLCS precomputes thumbnails, the ones from DLCS are faster to retrieve.

Using information from METS means we have thumbnails for more WorkTypes values than before, but even for WorkType 'q' and 'k' some of them might come from DLCS now.
If this problem is in any way related to the new source of thumbnails, then restricting the WorkType values won't fix it.

(One thing to note is that thumbnails from DLCS are in a 200*200 box rather than 300*300 as the ones from Loris.)

**Comment by davidpmccormick** [comment]
@gestchild has fixed this (although we're not currently displaying the images)
