### ISSUE TITLE
Rationale for continued use of Google Tag Manager

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4997]
We've had Google Tag Manager on the site since late 2018, but we feel we're not getting any real value from it.

We need to revisit rationale for implementing GTM in the first place and decide whether those are reasons enough to continue its use.

- What are the benefits/disbenefits of using GTM?
- Is GTM necessary for us to track traffic from wellcomelibrary.org to wellcomecollection.org as we tip the balance of usage? 
- Agree whether to keep and actively use or get rid of it

**Comment by taceybadgerbrook** [comment]
Google Tag Manager was originally introduced to create a data layer to allow analyse cross-domain WL/WC traffic without double counting.   While wellcomelibrary.org still exists, I feel the Data Layer is not useful.  Once wellcomelibrary.org is closed, the Data Layer will become obsolete.  

Comparison of old collection and library stats with the new data layer stats show the data layer is somehow filtering out certain users so that stats are lower.  So far I have not been able to identify where the filtering is occurring.

As quarterly statistics Data Studio reports were set up using the old accounts, I have chosen not to update these to draw on the Data Layer in favour of data continuity.  It's important to acknowledge that double counting is present but this seems less of an issue while wellcomelibrary.org is wound down because monitoring is focussed on the trend to increased support for wellcomecollection.org.

Another benefit of GTM is that it enables events to be tagged without incurring work for David and Gareth.  It has already been used to create the WordCard event in the old collection account. 
 This facility is useful for testing the performance of new features but might not be suitable for quarterly reporting as analysis is by event and not user.

I recommend we discontinue the use of GTM for the Data Layer but retain use for the old collection.

**Comment by jennpb** [comment]
@taceybadgerbrook With the recommendation to discontinue use, is there any work that needs to be done to remove GTM code from wellcomecollection.org? 

If so, we need to action it so this ticket can be closed.

**Comment by jamesgorrie** [comment]
@jennpb [there's a small amount of work that needs doing](https://github.com/wellcomecollection/wellcomecollection.org/pull/5140)

To be clear here though, if we remove GTM we will also stop reporting to the `Wellcome Collection and Library (UA-55614-24)`.

![ga-gtm](https://user-images.githubusercontent.com/31692/75329939-73c79180-5878-11ea-86e9-d298a5486125.png)

I knew we wanted 1 GA account, I'm just not aware as to which one.

**Comment by jennpb** [comment]
One for @taceybadgerbrook to confirm. My opinion is that if we're not using the data anyway, then it won't matter, but I don't know of any additional implications for not collecting that data.

**Comment by taceybadgerbrook** [comment]
From what I've read about GA v2 (currently called, "App and Web" but this may change) this wholly event-based and requires Google Tag Manager to set up the events.  I plan to open a v2 account for UA-55614 so that we have historic data by the time v1 is deprecated (with the help/advice of @davidpmccormick , @gestchild and @jamesgorrie of course.)

The current GTM container is not being used but please keep the account.  We'll need to create a new container for the GA v2 account.

**Comment by jamesgorrie** [comment]
> The current GTM container is not being used

@taceybadgerbrook it is to populate `UA-55614-24` and it uses tag manager in the way you explain for V2.

Happy to explain in person if that's easier.

**Comment by taceybadgerbrook** [comment]
Ok, we can cover this in this week's chat.  How about Friday?

**Comment by jennpb** [comment]
@taceybadgerbrook Can you point me in the direction of anything that says we must move to App+Web even if we don't have a mobile app? I've read a few things about this but nowhere does it say that it will be mandatory unless you are cross-platform tracking (e.g. your company's mobile app and website).

**Comment by jennpb** [comment]
So is my understanding that:
- GTM as currently used wasn't useful because we weren't really monitoring the property that combined Library and Collection sites
BUT
- GTM forms the basis of the GA App+Web product, outlined [here](https://medium.com/sparkline/google-analytics-roadmap-for-tracking-web-and-mobile-app-3b40f649d5c2), and thus will be used but only as associated with the account that @taceybadgerbrook sets up for GA v2

Can @taceybadgerbrook and @jamesgorrie let me know if I've understood?

**Comment by taceybadgerbrook** [comment]
Yes, this is my understanding.  If we want to check out GA App + Web, we'll need to be able to use GTM.
