### ISSUE TITLE
Works: Aligning landscape images in main view mode

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5097]
# What is it and who's it for?
People using image-based digitised material

# Problem to solve
When a manifest contains and/or starts with an image in landscape orientation, the image is only partially visible on loading the main view.

![landscape_mainview](https://user-images.githubusercontent.com/1446139/74441668-26a2f300-4e68-11ea-9ca6-7ac227829a21.png)
https://wellcomecollection.org/works/prrf9sds/items?canvas=1&langCode=eng&sierraId=b19743919

More examples: 
https://wellcomecollection.org/works/whx739wg/items?canvas=1
https://wellcomecollection.org/works/m8a4zfsh/items?canvas=385&langCode=en

Are there any solutions to align the top of the image with the top of the viewing area?

**Comment by davidpmccormick** [comment]
We're using a [`FixedSizedList` from react window](https://react-window.now.sh/#/api/FixedSizeList) to virtualise display of canvases in an item for performance reasons. In order to do the maths required to provide us with the performance benefit, each list item containing a canvas in the list is necessarily a square element, regardless of the canvas dimensions, and the canvas is vertically centred within that square. When we scroll to an item in the list, we go to the start of the list item, so that the list item is aligned with the top of the viewport. For landscape canvases, this can result in the canvas being shunted off the page downwards, increasing with the width of the viewport.

![IMG_6322](https://user-images.githubusercontent.com/1394592/112356858-e6e34780-8cc6-11eb-9221-c42c95b82415.jpg)

There is an option to center the list item vertically but, 1. [it doesn't work near the start/end of lists](https://github.com/bvaughn/react-window/issues/441) and 2. there are no guarantees that we wouldn't end up with some of the first canvas scrolled off the top of the page, which would look more confusing.

**Comment by pollecuttn** [comment]
@davidpmccormick can this be closed now?

**Comment by davidpmccormick** [comment]
It can. I meant to say in standup. I will.
