### ISSUE TITLE
Works & Viewer Page component annotations

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#5181]
# What is it and who's it for?
Annotated versions of the Works page and Viewer page under Collections for the digital team 
# User story
In order to _(why? accomplish a goal/get a benefit)_
understand what each component/page is under Collections

As a _(who? user/persona)_
digital team member

I need/want/expect _(what? to do this thing)_
I need to know what the common language/terminology is for the different components and define what the purpose of each thing is
## Acceptance criteria

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
Annotated pages now on Zeplin under the "Components Annotations" tag: https://zpl.io/2vpERZQ

**Comment by pollecuttn** [comment]
## 2 - Search page

:grey_question: Dropdown buttons/select: wondering if these should be what they are (filters, sort) or how they do it (dropdown buttons, select)

Search results -> Search results total

:grey_question: Search result card: creator, rather than author?

## 3 - Works page

About this work - also includes creator
