### ISSUE TITLE
Decide on and implement tracking for requesting items on works

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5191]
Things that _could_ be tracked

- Click ‘Log in to request’ button when logged out
  
![log in to request](https://user-images.githubusercontent.com/1394592/77532589-116cab80-6e8d-11ea-85e1-9af328f4d2c2.png)

- Click ‘Request’ button once logged in to launch modal
- Check/uncheck items before launching the modal

![multiple pre-modal](https://user-images.githubusercontent.com/1394592/77532671-36611e80-6e8d-11ea-8f80-ee39a7fda645.png)

- Close modal (without requesting anything)
  - Via clicking outside modal
  - Via clicking close cross
  - Via clicking ‘cancel’
- Check/uncheck item in pre-request list
- Click ‘Request to view in library’ button

![modal multiple](https://user-images.githubusercontent.com/1394592/77532706-51339300-6e8d-11ea-977b-acfbaf44c12f.png)

**Comment by davidpmccormick** [comment]
@taceybadgerbrook I've added an (I think exhaustive) list of things I think are trackable for the requesting service – see the points and screenshots in the description above.

Which, if any, of these do you think it would make sense for us to track, and what information would we want to capture if/when we do?

**Comment by taceybadgerbrook** [comment]
@davidpmccormick looks good but can you send me a link to the design so I can check for any other interractions?

**Comment by davidpmccormick** [comment]
Here are [the wireframes](https://app.zeplin.io/project/5aab926b4b6efde01259e959/dashboard?tag=Request%20wireframes).

**Comment by taceybadgerbrook** [comment]
I can't get into Zepelin...

**Comment by pollecuttn** [comment]
@taceybadgerbrook Try now - you should have access.

**Comment by taceybadgerbrook** [comment]
Roger that.  We have lift off!

**Comment by taceybadgerbrook** [comment]
I think the list looks fine except for the closing modal events.  If they close it, they don't hit request.  If we monitor the request button, we capture everyone who selects and requests and those who abandon.

Some questions:
1. If you aren't a library member and you decide you want to request something, shouldn't there be a screen taking you to the registration screens?
2. Are the selects and unselects going to be differentiated?  All I really need is an event where there are more selects than unselects to know whether a user has chosen anything to request.
3. Has the request to view in library button been replaced by the Request button?  All I need to monitor is whether a user confirms their request.

**Comment by davidpmccormick** [comment]
I think question 1. is out of scope for now – we're just dealing with people who are already members.

We don't allow you to continue if you don't have anything selected (we prompt you to make a selection) so I think that deals with question 2?

The 'Request' button launches the modal window, in which the 'Request to view in library' button resides. So the 'Request' button doesn't _actually_ do the request, but moves you a step closer to confirming your request.

So from your comment and what we discussed in peer review, I think there are three possible stages of the requesting process where (following an e-commerce pattern) we would want to track conversion:

1. From logged-out to logged in
2. From logged-in to launched modal (initiated request)
3. From launched modal to confirmed request

I don't think the url changes (or changes enough) for us to be able to track these things without using events.

So I _think_ we would need to set up an event funnel in GA to track each of these consecutive steps in order to measure conversion rate.

Also, you only have to log in once, so the event funnel should take that into consideration?

**Comment by davidpmccormick** [comment]
@taceybadgerbrook the three events will be added in #5213. They are:

1. `category: Button, action: 'follow Cognito login link', label: ${workId}`
2. `category: Button, action: 'open Stacks request modal window', label: ${workId}`
3. `category: Button, action: 'confirm Stacks request', label: 'item id(s): ${commaSeparatedListOfRequestedItemIds}`

I'll tag GA when this PR is merged and deployed.
