### ISSUE TITLE
Add requesting components to cardigan

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5193]
- [ ] ItemRequestbutton
- [x] Modal
- [x] ResponsiveTable

**Comment by davidpmccormick** [comment]
`Modal` is in Cardy and #5201 adds the `ResponsiveTable`. From the perspective of markup, the `ItemRequestButton` is just a button (which already exists in Cardigan) and since it is highly specific and doesn't make sense outwith the context of functioning as a button that initiates the requesting of an item, we agreed that it probably doesn't belong in Cardigan.

So I think this can be closed once #5201 is merged.
