### ISSUE TITLE
Improve image credit component to better handle caption and credit together

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5267]
# What is it and who's it for?
Editorial team

We currently use the TASL model to add a credit to images. This works fine for materials from our historical collections, but not necessarily for commissioned editorial images where the image's title is not the title of a work, but rather descriptive.

Two recent examples:

![image](https://user-images.githubusercontent.com/1446139/80569892-b846e900-89f1-11ea-80e9-e42072ae7dc3.png)

(this is not Kevin Percival. He's the photographer)

![Screenshot 2020-04-29 at 08 16 59](https://user-images.githubusercontent.com/1446139/80570000-edebd200-89f1-11ea-98ee-95f08e9e13a2.png)

Kathleen Arundell is photographer.

We need to:
- Improve the formatting of the credit so there's a clearer distinction between the Title/Description and Author/Creator
- Find out whether Editorial team also need to add a separate caption in order to describe the image.

Slack convo with Ben: https://wellcome.slack.com/archives/C3N7J05TK/p1587744073081300
and Alice https://wellcome.slack.com/archives/C294K7D5M/p1588144902038100

**Comment by LFBaily** [comment]
Not sure this is still an issue eg. some image credits have resolved this using this format: 

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/152871676/ba9ca590-a374-4ab2-b38b-e5d3738d222d)

**Comment by rcantin-w** [comment]
It still happens [here](https://wellcomecollection.org/articles/XnyS3BIAAIPxpVyI) (example sent by Ben in the Slack convo) so I wonder if they've started adding "Photo:" manually to make it clearer. Might be worth a Tasl review.

I couldn't find that specific picture in your example because the Prismic media library search is horrendous, but from another picture here I can see it's been done manually;
<img width="388" alt="Screenshot 2024-02-13 at 09 48 21" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/2376d318-38be-4787-844c-4e0a435804e5">
