### ISSUE TITLE
Content + UX - Visit Us design improvements

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#5317]
# What is it and who's it for?
Wireframe/page design improvements for the Visit Us page

## Acceptance criteria
- Wireframe of Visit Us page
- Content and components review
- Landing page can be created in Prismic
- Cards can be grouped on Landing Page

**Comment by DominiqueMarshall** [comment]
@GarethOrmerod @jennpb @davidpmccormick  Links to the Visit Us wireframe and content are below:
**Visit Us page wireframe Zeplin link:** https://zpl.io/VQj0doA

**Planning a visit (grouped content):** https://zpl.io/aXxYmvX

**Things to do and see (grouped content):** https://zpl.io/bzg8jZ3

On the main wireframe I've posted some notes about what the different sections are. Questions and feedback welcome!

**Comment by DominiqueMarshall** [comment]
Visit Us page wireframe: https://zpl.io/b6z1GNm

**Comment by jennpb** [comment]
**Production Scenarios**

Consider whether it's appropriate to give control to content team, or whether we take this on as an improvement task when new content is added or requests for change come.

- Content team create a new content page and they want it to appear as a standalone card.
- Content team create a new content page and want to add it to a card group. 
- Content team want to reorder cards within a grouping
- Content team want to reorder groupings
- Content team want to create a new grouping of 2 or more cards

**Questions**
What determines card size?
- Is it order on page?
- Number of cards in a grouping?
What determines background colour?

**Design comments**

Cosmic latte version https://zpl.io/VDEBxm3
- What happens if Building services are moved into Plan a visit group? Does Hire a Venue keep same size? Does it become a hero card?
- What happens if we turn Things to do and see into a 3-card group (What’s On, Research Library, Reading Room)? Does it still retain the idea of having a hero in that group, or do they all have the same size?

Yellow/Purple https://zpl.io/bWoq67K
Intriguing use of yellow box as background to featured content (address and times) and hero image. How might this work with section-level pages that don’t have featured content?

Purple tint is intriguing and much better than our own purple, but we’d need to get a nod of approval from Brand (Lindsay Pentelow / Maz Dear)

**Comment by davidpmccormick** [comment]
Some things I _think_ we want to be able to accommodate from within Prismic:

1. Content team to be able to add a list of lists, where the outer list is 'sections' like, 'Things to do and see', and the inner lists are groups of pages (represented as cards) related to that section
2. Cards within lists should be able to be added/removed/re-ordered within Prismic
3. Inner lists should be able to feature one item as hierarchically more important (larger, at the beginning) than the rest in that list
4. We want the approach we take for the 'Visit us' page to scale to other top-level pages (a) so we don't have to re-do the dev work for every page, and (b) to help ensure a degree of consistency across sections

Things I'm not sure about:

5. What should govern the difference in grid layout between sections? Can this be solely determined by the number of cards within that section?
6. How can we manage what background colour a section should have? Could it be a predetermined pattern, e.g. first section: white background, second: beige, third: white, fourth: charcoal, repeat? And if so can this pattern be the same for all top-level sections?
7. How can we manage what colour/style cards are within sections? Can this be determined solely by the background colour of the section they live in (e.g. if the background is white, the cards have a beige background, if the background is beige, the cards have a white background)
8. An extension of 7. – how can we/should we allow for a featured card to have a specific background (e.g. yellow in the 'Accessibility' card in [this design](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5ef20cdc8b91682abd40a5dc)

So far, 1. and 2. should be straightforward-ish to accomplish with what we have (or close to what we have) in Prismic already with the concept of 'content list' slices. With a slight amendment to the 'content list' slice, we should be able to accomplish 3. by adding a flag that says, 'this list has a featured item'. We could do 5. by assigning different grids to different numbers of cards.

The rest, I'm not sure how we should do without forcing the content team to make arbitrary design decisions (something we should try hard to avoid).

**Comment by pollecuttn** [comment]
Wireframes for section-level pages headings headings - @GarethOrmerod

**Comment by jennpb** [comment]
Nearing the finish line, some Content + Dev things to hash out now that it's possible to create a `landingPage` type in Prismic
https://docs.google.com/document/d/126CxYCWEoBgNr_k-ES2nEfTh96BEUO0-tR_roSpJuJ0/edit?usp=sharing

**Comment by jennpb** [comment]
We've reached a consensus that, because Exhibition and Events list pages are quite sparse and would need a bit more work to make 'destination' pages worth featuring on a card, that a card for What's On is more appropriate.

@gestchild @davidpmccormick Can you decide how you want to deal with this, given that What's On isn't a Prismic page? Is there a way to add a card for a non-Prismic page, and allow for a Title, summary text and image? 

Or are we better off making What's On a Prismic page that has editable components? Then treat it like the other landing pages?

**Comment by davidpmccormick** [comment]
> Can you decide how you want to deal with this, given that What's On isn't a Prismic page?

We have non-dynamic `Card` content type which I think fits the bill for this well. I think all we would have to decide is what the appropriate image would be for a What's On card – I'll check with Ben.

**Comment by jennpb** [comment]
Relates to KR wellcomecollection/platform#4646
