### ISSUE TITLE
Reorganising Gitbook documentation for Search 

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5386]
To enable easier navigation, the [Search documentation](https://app.gitbook.com/@wellcomecollection/s/catalogue/search) needs more clearly-labeled sections:

Page name | Content
-- | --
Collecting data | Existing
Hypotheses | To come from Intentions and expectations section and   Google doc
User Research | New.  Basic   summaries. Links to interview transcripts and Dovetail
Analysis | To come from Intentions and expectations section. Links to   Sharepoint docs
How it works | To house Expectations part of Intentions and expectations   section. Links to relevance tests used
Relevance tests | Existing
Reporting and metrics | Existing.  Looks   like ranking evaluation tests might become subpages of this section.

**Comment by jamesgorrie** [comment]
re: Hypotheses 

Would the process not be to have a hypotheses, test it qualitatively and quantitatively (ask people and look for examples of searches in the logs).

We would then have a verified intention, along with it's expectations?

**Comment by jennpb** [comment]
Are you intending to link to non-public Sharepoint docs? Is there a way to make this part more transparent?

**Comment by taceybadgerbrook** [comment]
Sharepoint docs are not publicly visible, so analysis results files would form (yet another) part of the Gitbook.  Are the non-analysis examples in the Google doc taken from user research? If so, I'd like to note this in Gitbook.

**Comment by jennpb** [comment]
Yes, all examples are either from the search logs or from user research and qualitative data collection.

**Comment by taceybadgerbrook** [comment]
New sections have now been created in GitBook. These will be visible after page text submitted.

**Comment by taceybadgerbrook** [comment]
Here is a link to Gitbook:
https://docs.wellcomecollection.org/catalogue/search

**Comment by taceybadgerbrook** [comment]
Maintainence of Gitbook is intended to be light touch. 
Gitbook document | Who does what
-- | --
Guide to wellcomecollection.org query development | James/Harrison: inform Tacey of changes to queries and   impact on the kinds of things people search for
  | Tacey: update links 
Hypotheses pages | Tacey: add pages for new hypotheses
Analysis pages | Tacey: add page for new analysis summaries
Query design search strategy glossary | Tacey: update if new strategies deployed
Relevance tests | James/Harrison: update with results of testing
Reporting and metrics | James/Harrison: finish drafting

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @jennpb could you have a look at the Guide and let me know what you think?

**Comment by jennpb** [comment]
Just a few comments/questions from me:

----
https://docs.wellcomecollection.org/catalogue/search
Some of the narrative on this page refers to a single moment in time, or maybe not quite true now. 

> The single point of interaction (the search box) and often hundreds of pages of results to sift through leaves users frustrated, feeling a lack of control over the interface and a weakening trust in the system as a whole.

This was a hypothesis from 2019, but there's no indication that people are currently frustrated by a single search box, or by the number of results pages.

> Explicit data collection: users are told that they are part of an experiment, and providing us with information is their primary motive.
Some of the data we've used to measure search relevance is collected in sessions with internal users who know the collection well and the kind of things that people / researchers might be looking for, following a set of instructions to obtain data in a useful format.
This data is small (20-50 rows per person, per session, with ~10 people taking part), but can be deeply contextualised by talking to the people who took part.
We're now ready to start collecting explicit feedback through an opt-in mechanism on wellcomecollection.org/works, with all users given the option to rate the relevance of individual results in relation to their query.

This refers to the first two types of explicit data collection we conducted in 2019. Maybe this can be reframed to talk about the types of explicit data collection we can and have done? This would include diary studies, like those that Alice is doing, or asking users to provide their real life search queries, and apply a ranking to them. Another way we've done it is by having an opt-in relevance ranker, allowing those who wanted to rank search results could do so (but this had very low take-up). As written, it sounds like these two explicit data collection mechanisms are either still in use, or the only way to do it.

----
https://docs.wellcomecollection.org/catalogue/search/query-development-guide
It might be a bit clearer if this was called `Index` rather than `Guide`. Guide implies we're telling how something was done, but this is more like an index of references? Just my opinion though!

----
https://docs.wellcomecollection.org/catalogue/search/hypotheses/further-research-and-design-considerations
This one doesn't feel much like documentation but more like an ideas dump (which it was). I think it needs to be anonymized (taking out specific references to WMS/William or any other user names). 

----
https://docs.wellcomecollection.org/catalogue/search/analysis
This feels like it's part of the Guide/Index, rather than a standalone page under Search?

**Comment by pollecuttn** [comment]
@taceybadgerbrook Are you happy to close this now?

**Comment by taceybadgerbrook** [comment]
@pollecuttn - sorry, no. I didn't see Jenn's comments, so will address these today.

**Comment by taceybadgerbrook** [comment]
Changes to text in Search and Further considerations made in https://github.com/wellcomecollection/catalogue/pull/849.

Changed name of Guide to Index using Gitbook UI. Seems to have worked ok.

The Analysis section appears under Search as the analysis is confined to search behaviour and functionality. Collecting this into one area allows users to check how/whether we have made data-informed decisions.

**Comment by taceybadgerbrook** [comment]
Gitbook link and guide on how to update it now housed in Notion. 

@jamesgorrie, @davidpmccormick / @gestchild could you have a look at the instructions and let me know if the [instructions for updating Gitbook](https://www.notion.so/wellcometrust/How-to-update-Gitbook-66d028f9c2c047d0bd50a77fcd7d2ebb) make sense?

**Comment by pollecuttn** [comment]
@jennpb Tacey said this is just waiting in case you have comments, if not it can be closed (you've talked with Tacey about this ticket) - thanks.
