### ISSUE TITLE
Researching filtering 

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5483]
**We think that**

If the Search team provide users with a range of filters, users will find what they are looking for within the collection more easily

**Therefore we hypothesise that**
By adding filters for
- availability
- subject/genre
- license type
- author 

Users of the Wellcome Collection.org site will be able to locate their items of interest with more ease

**As measured by**

- Number of participants correctly identifying the filter functionality in moderated tests
- Number of website users entering works pages

**We are right if**

Users find more items that they are looking for

**Comment by alicerichmond** [comment]
@taceybadgerbrook we need to chat about what metrics we want to gather and how we should do that to ensure that we are making effective change

**Comment by taceybadgerbrook** [comment]
Here is what I found when I looked at the data I collected on initial searches not derived from Google or other search engine activity:

![image](https://user-images.githubusercontent.com/32418070/92128606-793eff00-edfa-11ea-9dbb-2888f23b5a42.png)

I think there is enough evidence to support provision of date and image filters.

**Comment by taceybadgerbrook** [comment]
To evaluate the success of any filters that are introduced, either filter usage and viewing need to be tracked in Elasticsearch or we are stuck with using GA to monitor filter usage and attributing any increased views of works to the new filter. This is a big assumption.

The reason is because GA cannot trace a user journey. I can get GA to produce stats on total users who use a filter (providing this event is tagged appropriately) and total users who view a work by workId but I can't segment for users who use a filter and then produce stats on those who view a work.

**Comment by taceybadgerbrook** [comment]
I’ve been looking at GA Goal funnels to evaluate conversion rates for searches with filters.  GA seems to chop out the query bit of the URL for workType but not for dates.  Maybe it can only handle so many query elements in a typical URL? This might be at the heart of why Kibana started being used to evaluate search behaviour. 

In addition, I can’t include downloading digital images in a goal funnel because users pass through the https://iiif/wellcomecollection.org which is a different domain from wellcomecollection.org.

@jtweed - Success for filter usage would mean filter users find what they need higher up in the page position and so have a lower median page depth. I will need Elasticsearch to pick up filter usage to conduct this analysis.

**Comment by jtweed** [comment]
Thanks @taceybadgerbrook, I am keen that we measure the use of filters. In particular so we can use that to influence the ordering of filters on the page, as we might end up with quite a few. As you say, we should also see which ones influence the other click metrics the most too.

Let’s pick this up in planning, to make sure it gets considered as part of the work to add the filters.

**Comment by taceybadgerbrook** [comment]
Some thoughts on how the filters could affect the data:

People might start out thinking they only want items online for example but then change their mind depending on the results served and spend time trying out different combinations of availability and images/people/subjects/formats. This would result in increased numbers of searches and lower click through rate.

In addition, a user might decide that the combination of filters they used 5 minutes ago was the best but not remember exactly what that was.  They may search even more trying to find what that combination of filters was.

As a consequence removing the topic buttons, searches might decrease because users have to work harder. To check whether this is a risk at all, I could look at subsequent searches following topic button usage.

**Comment by taceybadgerbrook** [comment]
To test whether removal of the topic link buttons make users panic and leave, I analysed the percentage of exits to unique page views, combining data for both "wellcomecollection.org/works" and the new homepage,  "wellcomecollection.org/collections."  

The graph below shows weekly percentages for the period 30/8/20 - 21/11/20

![image](https://user-images.githubusercontent.com/32418070/100091086-0ae36900-2e4c-11eb-975e-9e69495b34a4.png)

The topic buttons were removed 13/10, the week indicated by the red arrow. It does appear that increased percentages of users are exiting from the collection homepage following removal of the buttons.

**Comment by taceybadgerbrook** [comment]
Next steps: 
- to use Kibana to analyse the behaviour of users who filter
- to use these observations as the basis for more research or changes in the way filters are presented

https://github.com/wellcomecollection/wellcomecollection.org/issues/5833
