### ISSUE TITLE
Acquisition strategy: high value users

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6536]
**What is the problem to solve?**
The acquisition strategy is about attracting more users. One way to do this is to make the site more attractive.

**What stage of research is it? (discovery/general usability testing/post release)**
discovery

**What are the objectives?**
 If we can identify the activity of users who value the site most, we can identify what elements of the site that make it a compelling proposition.

**What are the assumptions?**
Researchers who come to the site are already motivated to spend time on site. This research is about the kinds of users who come to the site without an agenda.

High value users:
- spend the most time on site
- have longer average session duration time
- are likely to return

**What research technique is required?**
GA segmentation
Hotjar (maybe)

**Actionable results/areas to test with UR**
Are there differences in design of popular/unpopular list pages?
Are some types of content more popular than others?
Do users click on links or rely on the main navigation?
Are there areas where new users shy away from? and how could we make these more "welcoming?"

**Comment by taceybadgerbrook** [comment]
Analysis period: 1/1/20 - 28/2/20. This is to capture a high-volume, pre-pandemic period when users were coming to the site to find out about opening times, events and exhibitions.

**Comment by taceybadgerbrook** [comment]
High value users defined as having average session duration of more than 2 minutes (which is above average), account for 13% of total users but 62% of total page views. When sorted by highest number of page views and time on page, the majority of these users are shown to be viewing stories.

Segmenting further as average session duration of more than 2 minutes and having viewed pages containing /articles/, traffic sources for these users are 42% Google/organic search, 19% Facebook/referral and 9% Twitter/referral.

**Comment by taceybadgerbrook** [comment]
Are Stories being represented on Google as well as they could be? A quick look at the top 4 stories from the last 28 days shows that 2 appear on Google with subtext that adequately reflects the story, probably because this was attached as metadata. However, 2 appear with subtext taken from the first sentence preceding the first link. This text is far from enticing.

@dannybirchall if all stories aren't tagged with appropriate metadata, we're likely to be missing out on potential readers.

**Comment by dannybirchall** [comment]
Hi Tacey

This should be in there as standard.  Can you send me a screenshot/tell me which ones are apparently missing their promo?

Thanks

Danny




Sent from Samsung Mobile on O2



-------- Original message --------
From: Tacey ***@***.***>
Date: 28/05/2021 16:09 (GMT+00:00)
To: "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Danny Birchall ***@***.***>, Mention ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Acquisition strategy: high value users (#6536)


Are Stories being represented on Google as well as they could be? A quick look at the top 4 stories from the last 28 days shows that 2 appear on Google with subtext that adequately reflects the story, probably because this was attached as metadata. However, 2 appear with subtext taken from the first sentence preceding the first link. This text is far from enticing.

@dannybirchall<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdannybirchall&data=04%7C01%7Cd.birchall%40wellcome.org%7C74931a37c3884d86900308d921ea9ad5%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637578113776959325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jAX%2FMqlQt%2B%2FBydLj2X6f2M9uWMb5%2FI1xS%2FWPbeVBaG8%3D&reserved=0> if all stories aren't tagged with appropriate metadata, we're likely to be missing out on potential readers.

**Comment by dannybirchall** [comment]
Also, can you tell me more about 'acquisition strategy'?

D



Sent from Samsung Mobile on O2



-------- Original message --------
From: Danny Birchall ***@***.***>
Date: 28/05/2021 16:16 (GMT+00:00)
To: "wellcomecollection/wellcomecollection.org" ***@***.***>, "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Danny Birchall ***@***.***>, Mention ***@***.***>
Subject: RE: [wellcomecollection/wellcomecollection.org] Acquisition strategy: high value users (#6536)

Hi Tacey

This should be in there as standard.  Can you send me a screenshot/tell me which ones are apparently missing their promo?

Thanks

Danny




Sent from Samsung Mobile on O2



-------- Original message --------
From: Tacey ***@***.***>
Date: 28/05/2021 16:09 (GMT+00:00)
To: "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Danny Birchall ***@***.***>, Mention ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Acquisition strategy: high value users (#6536)


Are Stories being represented on Google as well as they could be? A quick look at the top 4 stories from the last 28 days shows that 2 appear on Google with subtext that adequately reflects the story, probably because this was attached as metadata. However, 2 appear with subtext taken from the first sentence preceding the first link. This text is far from enticing.

@dannybirchall<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdannybirchall&data=04%7C01%7Cd.birchall%40wellcome.org%7C5d2775c4625946de4d9d08d921eb8643%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637578117716775221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SAS3cKs1ZcnN7cCfiaLKQYnIV6U1YhEkygBsNS1G14Y%3D&reserved=0> if all stories aren't tagged with appropriate metadata, we're likely to be missing out on potential readers.

**Comment by taceybadgerbrook** [comment]
Coming your way!

From: Danny Birchall ***@***.***>
Reply to: "wellcomecollection/wellcomecollection.org" ***@***.***>
Date: Friday, 28 May 2021 at 16:16
To: "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Tacey Laurie ***@***.***>, Assign ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Acquisition strategy: high value users (#6536)

Hi Tacey

This should be in there as standard. Can you send me a screenshot/tell me which ones are apparently missing their promo?

Thanks

Danny




Sent from Samsung Mobile on O2



-------- Original message --------
From: Tacey ***@***.***>
Date: 28/05/2021 16:09 (GMT+00:00)
To: "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Danny Birchall ***@***.***>, Mention ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Acquisition strategy: high value users (#6536)


Are Stories being represented on Google as well as they could be? A quick look at the top 4 stories from the last 28 days shows that 2 appear on Google with subtext that adequately reflects the story, probably because this was attached as metadata. However, 2 appear with subtext taken from the first sentence preceding the first link. This text is far from enticing.

@dannybirchall<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdannybirchall&data=04%7C01%7Cd.birchall%40wellcome.org%7C74931a37c3884d86900308d921ea9ad5%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637578113776959325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jAX%2FMqlQt%2B%2FBydLj2X6f2M9uWMb5%2FI1xS%2FWPbeVBaG8%3D&reserved=0> if all stories aren't tagged with appropriate metadata, we're likely to be missing out on potential readers.
