### ISSUE TITLE
Priority 1 accessibility issue: Works page focus order

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6549]
**What**

On page load, focus is immediately taken into the middle of the page as a control is automatically focused. This may be navigationally disorientating for users who would expect to be taken to the beginning of the page.

Solution:
Remove the ‘autofocus’ attribute so that users may proceed as expected through the page in reading order, from top to bottom, and left to right.

Code refs:

<img width="523" alt="Screenshot 2021-05-27 at 14 36 39" src="https://user-images.githubusercontent.com/7315126/119835684-f5352600-bef8-11eb-827b-cdac978d9900.png">

**Where**

URL: https://wellcomecollection.org/works/h8cskpec
Page title: On the origin of species by means of natural selection : or The preservation of favoured races in the struggle for life / [Charles Darwin]. | Wellcome Collection

**Comment by gestchild** [comment]
This needs discussion @alicerichmond @DominiqueMarshall 

[Adding the autofocus](https://github.com/wellcomecollection/wellcomecollection.org/pull/3935) was intentional following user feedback: https://github.com/wellcomecollection/wellcomecollection.org/pull/3935#issue-243613687

The accessibility concerns were noted at the time and mitigated with the use of aria-describedby on the form to give context.

This pattern seems reasonable, when the purpose of the page is the form. However, this isn't true of /works and /collections now carries a lot of additional content too.

**Comment by gestchild** [comment]
We discussed this with Sarah from DAC, who asked some screen reader users for their opinions. They responded as follows:

‘Personally, I would rather focus started at the top of the page rather than in a search field.’
‘In general, it would be a problem, but looking at it in context, the ‘search’ field is the main purpose of the page so it doesn’t bother me too much.’
‘I would prefer it if focus went to the top of the page. I could navigate to what I wanted then.’
‘I would say that the fact that the screen reader focus is automatically taken to the search field is problematic because it is disorientating. This would affect experienced and new users alike, but may be especially confusing for new users who, as well as not knowing where they are on the page, may not know what occurred on the screen.”
I think from these comments, my impression would be that it is not the preferred behaviour and that it may cause issues to some users.
 
Many thanks,
 
Sarah

**Comment by gestchild** [comment]
It seems we have competing needs from different user groups. @alicerichmond how do you think we should proceed with this one?

**Comment by alicerichmond** [comment]
I think that we should make the focus the top of the page if this is the case.
If there was only a search box alone on a page like the google home page it might be suitable, but because the pages with the search bar on offer other contents we are masking that by autofocussing on the search bar. That would be problematic for users if they needed the other content, such as library membership etc. 

I will kick off the search bar heat map again once this has been done to make sure that we dont cause any other usability issues.
