### ISSUE TITLE
Free label obscures Library Sign in

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6831]
**What**
The `Free` label position obscures the `Library Sign in` when on e.g. [an exhibition page](https://www-stage.wellcomecollection.org/exhibitions/YLjGYhAAACMAed2Z)

<img width="840" alt="Screenshot 2021-07-26 at 17 43 23" src="https://user-images.githubusercontent.com/36885440/127027031-bc0b6795-c11b-4ab1-991a-7529d28d8d1e.png">

As `Free` relates only to the exhibition there could be a more appropriate position, the current placement suggests that free is something global.

**Comment by davidpmccormick** [comment]
The Free label no longer obscures the sign in dropdown, but half of the Free label is now hidden behind the header (only with the `showLogin` toggle turned on).

#6825 fixes the problem while keeping the Free label where it currently is, but it is quite an involved fix, and I've left it in draft until we're sure that that is where we want to keep the Free label (because if it moves to a position that doesn't straddle both the header and the main area, then the fix would be simpler).

**Comment by davidpmccormick** [comment]
This has been solved by moving the Free sticker (#6919)
