### ISSUE TITLE
Disabled/loading state "Request item" button should be a lighter shade of grey

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6973]
It currently uses the existing `disabled` state, which looks a bit too heavy:
![image](https://user-images.githubusercontent.com/4429247/130988962-fc5ac8dc-3c92-4217-b731-3db4438a0167.png)

**Comment by DominiqueMarshall** [comment]
Potentially change the background colour of the disabled buttons to #e8e8e8 (smoke) and the text colour to #323232 (charcoal) as shown in the first button, or make the text colour even lighter (#8f8f8f) as shown in the bottom version.

@GarethOrmerod would you be able to double-check this, please?

<img width="1288" alt="Screenshot 2021-08-31 at 09 09 03" src="https://user-images.githubusercontent.com/60890140/131466665-cc1b249c-68af-4b6a-847a-09864b794cd5.png">

**Comment by GarethOrmerod** [comment]
@jamesgorrie There’s already a ‘not requestable’ message and there is a banner explaining you need to sign in to able to request. Could there be a ‘requestable’ message the same for those that are requestable. I can understand the frustration of displaying a CTA that you can’t interact with.

Otherwise the text on the disable button would need to be #323232 if we are being AA compliant.

**Comment by jamesgorrie** [comment]
@GarethOrmerod ah, OK, so I'll change the disabled button anyway.

I think what we're talking about here is state change and item is either:
* requestable
* not requestable

Then we need to do a look up to see:
* is a user logged in? Make item requestable
* Is a user isn't ???
