### ISSUE TITLE
Requesting: Load time - UI/UX

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7120]
**What**
Throughout the requesting journey there are noticeable delays in items loading.

Not only does this cause disruption in the user journey from a load time perspective but the experience whilst loading is also different throughout the journey (loading bar on login prompt, ... on text fields/button space, pause icon on account page).

We need to:

1. Explore the opportunity to reduce load time (Issue: #7118 )
2. Review the experience and at least make this smoother/more aligned across the journeys

Jamie added some commentary on #7118 around this being an opportunity for "optimistic ui updates" and provided some really nice examples: https://simonhearne.com/2021/optimistic-ui-patterns/

_Note: Have been testing on mac / home wi-fi. Will need to check mobile performance._

**Where**
Key locations I've noticed this (low/medium/high in terms of load times)

- After signing in - the login prompt on an item [medium] - loading as a loading bar
- After signing in - the access field/button on an item [high]- loading as previous text status and ...
- After signing in - account page [high] - loading as || icon
- After requesting - on confirmation overlay [high] - loading as || icon
- After requesting an item - the change in note [high] - loading as previous text status
- After signing in - the 'you're logged in' area in header [high] - no indication, showing as blank until loaded in

**Related to**
#7118

**Comment by jamesgorrie** [comment]
On @jamieparkinson's point of optimistic UIs\

That's kind of where we are in some instances e.g. the user login we can have the "library sign in" text, but then swap it out to "JG" when I am signed in, which is confusing. 

I think with this specific component, what is the optimistic state, especially as it's a small percent of users that we are going to expect to be logged in.

What makes this more difficult in the long run is that this will be on every page load for when you're on the content app (stories, what's on, other content pages).**

**Comment by jtweed** [comment]
Rather than creating a separate issue, I'd like to add my 2p to this one around the experience as item data loads from the requesting API and replaces the data from the catalogue API.

There's quite a bit of jumping around as this happens, especially for works with multiple items and it's kind of confusing as it all happens independently with each item coming in at different times, making it kind of confusing as a user until it's all done and all of the "Loading..." disappear.

I also think the "Loading..." is ill-considered and not a good enough design treatment, as it visually conflicts with both the other text that then doesn't disappear and the button elements that sometimes replace it.

I think we may also be able to additionally improve this by bypassing the data reloading for certain states, including open shelves, unavailable, unrequestable and manual request items. There's no need for us to eg hit the requests API 10s or 100s of times for a large journal that is mostly on the open shelves.

But I would check with @alexwlchan for the exact conditions as to when they think this could be short circuited to improve front end loading performance.
