### ISSUE TITLE
Issues with requesting modal and data flow

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#7137]
**What**

There are a few issues with the requesting modal and the general requesting flow, in particular how things update after a request is made:

- [x] The requesting modal is too wide at the largest breakpoint, resulting in line lengths that are too long. - fixed by #7147
- [ ] After a request is made but before the page is reloaded, the request item button gets replaced by a poorly placed "You have this item on hold" upon dismissal of the modal.
- [ ] This message is different on page reload, when that message is not there and instead an item note appears with similar but different worded info.
- [ ] More than once but not every time, I've got a message that I've requested something but the request item button is still shown.

**Where**

Modal too wide:

![Screenshot 2021-10-07 at 15 18 23](https://user-images.githubusercontent.com/42490/136441610-0ff61357-b46e-4f78-86dc-4403ee42c98a.png)

Rather lost and out of place message after making a request:

<img width="824" alt="Screenshot 2021-10-07 at 19 27 48" src="https://user-images.githubusercontent.com/42490/136442105-729f8578-9d58-4b99-ae7a-c978d41b2c28.png">

Different message on page reload, still showing the button:

<img width="815" alt="Screenshot 2021-10-07 at 19 28 07" src="https://user-images.githubusercontent.com/42490/136442127-a49adb2e-6163-4cde-b834-71e08cca07db.png">

**Comment by gestchild** [comment]
I've started a [branch for the remaining items in this issue](https://github.com/wellcomecollection/wellcomecollection.org/tree/requested-item-issues). All it does so far is remove the 'You have this item on hold' message, with the consequence that the button will show after a successful request has been made (not what we want).

To fix the issue with the button and the remaining issues on the ticket I think we need to request the items from the items API again, once the modal is dismissed. Then we can render the updated status of the item (meaning the access status will update, the button won't show and the Note telling you 'You have requested this item' will display, as it does on reload). The difficulty here is that the response from the items API doesn't seem to update quickly enough, so it appears that the item is still available immediately after the item has been successful requested.

My only thoughts are that because we know at this point whether a successful request was made, we keep checking the items API until we see the change in the response that we expect and then render the items. However, I don't know how long this would take and I don't know what we would show the user while that is happening.
