### ISSUE TITLE
Account - Change email address modal - Requesting

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7151]
**What**
When requesting to change email address via my account page, when I enter an incorrect password, the new email address I've entered has reverted back to my original email address. This isn't obvious to a user and because of the validation tick feels like it's the new email address (a user wouldn't necessary re-check)

Retain the newly entered email address if possible.

**Where**

Step 1: Enter new email address into 'New email address' field but enter an incorrect password
![image](https://user-images.githubusercontent.com/91600241/136929623-672b2768-a5a2-432f-9b45-cbc84d3008a7.png)

Step 2: Select update email address and wait for the error message about invalid password to load. The email address in the field has now reverted to the original email address of the account but shows a validated sign as though it's the new email address
![image](https://user-images.githubusercontent.com/91600241/136929894-d9786847-a608-466c-b136-4beb6cd30a2e.png)

**Comment by davidpmccormick** [comment]
Yeah, I agree the field doesn't feel like it should be pre-filled. Not sure about whether or not it should remain filled after an unsuccessful form submission. I think I'm leaning toward it remaining filled with whatever you'd entered so that e.g. if you'd made a one letter typo that made your email address invalid, you could see the problem and fix it with a minimum of keystrokes, rather than having to take our word for it that you'd entered an invalid email address and enter the whole thing again.

**Comment by DominiqueMarshall** [comment]
Current email visible (but not editable):
<img width="500" alt="Screenshot 2021-10-21 at 09 56 22" src="https://user-images.githubusercontent.com/60890140/138245307-84566516-256b-4c98-adf3-01effcbfcadb.png">


Old email entered & not updated:

<img width="500" alt="Screenshot 2021-10-21 at 09 56 50" src="https://user-images.githubusercontent.com/60890140/138245388-212358a7-b271-4940-a8e3-438e41c5c28a.png">



New email entered, but password incorrect. The behaviour would be the same as entering the old email, _i.e. user clicks the 'update email' button, but the error message shows rather than the loading icon:_

<img width="500" alt="Screenshot 2021-10-21 at 09 56 37" src="https://user-images.githubusercontent.com/60890140/138245348-37871c07-266a-4f65-b26e-56b5d7aece43.png">


The loading icon should only show when the email has been updated and the right password has been written.
