### ISSUE TITLE
Online requesting dashboard: tracking user journey 

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7431]
This ticket builds on #6787, setting out what dashboards would look like and what data is required

**We want to know if the following change has improved the user experience**
Online requesting

**Definition of success is**
Users able to navigate log in process, request items and collect holds

**We'll know if we're succeeding if we measure the following metric and this happens**
Count of view library account button clicks increases during first quarter
Count of confirm request item button clicks increases during first quarter
% total confirm requests / total works page views increases during first quarter
% total holds collected / total confirm requests increases during first quarter

**Definition of failure is**
Users unable to navigate log in process, request items and collect holds

**We'll know if we're failing if we measure the following metric and this happens**
Count of view library account button clicks does not increase during quarter
Count of confirm request item button clicks does not increase during quarter
% total confirm requests / total works page views does not increase during first quarter
% total holds collected / total confirm requests does not increase during first quarter

**Comment by taceybadgerbrook** [comment]
[Events in requesting service that can be monitored:](https://github.com/wellcomecollection/wellcomecollection.org/issues/6787#issuecomment-979065077)

- create library account (button on Apply for library membership page)
- resend verification email (button on Account created page)
- re-enter your email (link on Account created page)
- Contact the library (link on Account created page)
- request item (button click on works page)
- confirm request (button click on modal)
- book ticket (button click on modal)
- view library account (link click on different pages)
- sign in (button on sign in page)
- send password reset (button on library account page)
- change email request (button on library account page)

**Comment by taceybadgerbrook** [comment]
Evaluating log in processes

|Name of table/graph|How this might look|Data required in metrics-conversion-prod index|
|:-----|:-----|:--|
|1. Login numbers from header|![image](https://user-images.githubusercontent.com/32418070/144870132-3e848040-ec38-4b78-abf0-5fc819aafa4e.png)|Kibana metric and time series, counts by view library account button click, filtered by source:header|
|2. Login numbers from works page|![image](https://user-images.githubusercontent.com/32418070/144870551-55864d64-03be-4a51-9735-dddafac9b3b8.png)|Kibana metric and time series, counts by view library account button click, filtered by source:works page|
|3. Frequency of login|![image](https://user-images.githubusercontent.com/32418070/144874272-ae5ccc57-fa0c-4752-9e98-fe24c9e651b5.png)|Kibana metric and time series, average number of logins by library account (both logging in from header and /works page|
|4. Login problems|![image](https://user-images.githubusercontent.com/32418070/144873596-b0e8ae43-43a5-4f6a-b57a-a2813fcee0c6.png)|Kibana time series of forgot password link clicks, contact the library link clicks|
|5. Increases in library membership|![image](https://user-images.githubusercontent.com/32418070/144874982-5e02b60d-8750-4e37-bd37-2c0a8d8cf209.png)|Kibana metric and time series of clicks on Create library account button|

**Comment by taceybadgerbrook** [comment]
Evaluating requesting processes

|Name of table/graph|How this might look|Data required in metrics-conversion-prod index|
|:-----|:-----|:--|
|1.

**Comment by taceybadgerbrook** [comment]
Following conversation with @alexwlchan and @jamieparkinson , this looks like a tagging job for @davidpmccormick and @gestchild and tracking would take place in GA.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick , @gestchild , here's a summary of what we discussed:

Using GA to evaluate log in processes

|Name of metric|GA event details|Event to be tagged|
|:-----|:-----|:--|
|1. Number of account logins|Event category: library_login, Event action: click, Event label: url|when user clicks view library account button|
|2. Frequency of login|Needs to be aggregated by user. |Let's not collect this because it's PII.|
|3. Number of login problems|Counts of users forgetting password and contacting the library need to be collected from Auth0|No events to be tagged in GA|
|4. Number of library memberships created|Event category: join_library, Event action: click, Event label: url|clicks on Create library account button. Note: currently only existing library members can request items online|

**Comment by taceybadgerbrook** [comment]
Using GA to evaluate requesting processes

|Name of metric|GA event details|Event to be tagged|
|:-----|:-----|:--|
|1. Numbers of requests|Event category: online_request, Event action: click, Event label: url|when user clicks request button|
|2. Numbers of requests confirmed|Event category: request_confirmed, Event action: click, Event label: url|when user clicks confirm request button|
|3. Average number of confirmed requests per user|Needs to be aggregated by user. |Let's not collect this because it's PII.|
|4. Number of ticket bookings|Does this existing event meet this requirement? Event category: Outbound, Event action: click, Event label: url|when user books a ticket after confirming request|

**Comment by gestchild** [comment]
The work for this is here: #7668, but I have a few questions/should clarify some things:

I've implemented 1. and 2., under "Using GA to evaluate requesting processes" above, exactly as requested, but didn't bother with 4. as ticket booking is about to be removed.

With regards to 1. under "Using GA to evaluate log in processes" above. I was a bit confused as the event category is 'library_login' but the description is "when user clicks view library account button", which seem to be different things.

What I've done is add event tracking for library login, with the GA event details above, and separate tracking for following links to the account page, once the user is logged in. This uses the following GA event details.

` category: 'library_account', action: 'click', label: url`

In addition, there are several places from which a user can login/view their account, see below. At the moment, I'm using the same event tracking in each place, but **do we want to differentiate these?**

**Sign in link large screen:**
![Screenshot 2022-02-17 at 11 23 21](https://user-images.githubusercontent.com/6051896/154479142-2b3c40ff-62bf-4659-87ea-7c3e915ddb79.png)

**Sign in link small screen:** 
![Screenshot 2022-02-17 at 12 11 51](https://user-images.githubusercontent.com/6051896/154479360-b1d97b77-bd23-43a6-b2f5-6e686dd2e860.png)

**Sign in link on works page:**
![Screenshot 2022-02-17 at 11 24 37](https://user-images.githubusercontent.com/6051896/154479417-4cfa0e10-caf6-4c1e-914c-cc3ef7de3393.png)

**View account link large screen:** 
![Screenshot 2022-02-17 at 11 18 42](https://user-images.githubusercontent.com/6051896/154479483-ded637cc-025f-4e45-8624-5758512093b1.png)

**View account link small screen:**
![Screenshot 2022-02-17 at 11 18 57](https://user-images.githubusercontent.com/6051896/154479521-a5812811-23c0-4a34-830a-4c58e0f14619.png)

Lastly, **I just want to make sure we're happy with the `category` and `event` labels being used**. My understanding is the category should be used to group similar events, whereas the text for these look more like what should go in the action, rather than that being 'click'.

**Comment by taceybadgerbrook** [comment]
@gestchild @davidpmccormick  Thanks for implementing this. 

Regarding what to call the Event category for account logins, "library_account" makes sense to me. Regarding what to call Event action how about, "login" ? If we leave Event label as the url, this will allow me to identify which page users click on the button.

**Comment by davidpmccormick** [comment]
I'll update the PR such that the category is always `library_account` and the action is `view` when you're going to your account page and `login` when you're going to log in.

**Comment by taceybadgerbrook** [comment]
Thanks @davidpmccormick. So in summary:

**Using GA to evaluate requesting processes**

|Name of metric|GA event details|Event to be tagged|
|:-----|:-----|:--|
|1. Numbers of requests|Event category: online_request, Event action: click, Event label: url|when user clicks request button|
|2. Numbers of requests confirmed|Event category: request_confirmed, Event action: click, Event label: url|when user clicks confirm request button|
|3. Average number of confirmed requests per user|Not collected (uses PII.)|
|4. Number of ticket bookings|Not collected (tickets being discontinued.)||

**Using GA to evaluate log in processes**

|Name of metric|GA event details|Event to be tagged|
|:-----|:-----|:--|
|1a. Number of account logins|Event category: library_account, Event action: login, Event label: url|when user clicks button to log into library account|
|1b. Number of account views|Event category: library_account, Event action: view, Event label: url|when user clicks button to view library account|
|2. Frequency of login|Not collected (uses PII.)|
|3. Number of login problems|Not collected. LE&E to monitor.||
|4. Number of library memberships created|Not collected (only existing library members can request items online.)|

**Comment by davidpmccormick** [comment]
I'll reopen this till #7668 is merged and deployed. Then I'll add an annotation in GA so that we know when this was live.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick in keeping with the principle that event category should be more general, like ‘requesting’, and event action more related to the category, how about changing 1. and 2. to:

**Using GA to evaluate requesting processes**

|Name of metric|GA event details|Event to be tagged|
|:-----|:-----|:--|
|1. Numbers of requests|Event category: requesting, Event action: initiate_request, Event label: url|when user clicks request button|
|2. Numbers of requests confirmed|Event category: requesting, Event action: confirm_request, Event label: url|when user clicks confirm request button|
|3. Average number of confirmed requests per user|Not collected (uses PII.)|
|4. Number of ticket bookings|Not collected (tickets being discontinued.)||

**Comment by taceybadgerbrook** [comment]
These metrics have now been added to Reporting Schema #7187
