### ISSUE TITLE
Investigate / Resolve SameSite Cookies warning

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7503]
### Background

Alex flagged warnings from Web Inspector log in relation to cookies misusing the "SameSite" attribute and that the cookies impacted would 'soon be rejected'

If this rejects the cookie it would impact our GA reporting

### More info:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

We need to investigate the impact further and make relevant changes to the values to resolve the issues being flagged

**Comment by cbowskill** [comment]
Note: Can you ensure this doesn't go onto prod until @taceybadgerbrook  had a chance to review it / discuss %s to test with you

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @cbowskill I am looking at this as I am here for the day and on and off next week.

Reading [this article again](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite), I understand that SameSite is a setting that all Chrome, Edge, Firefox, Opera and Safari recognise and lately have required SameSite=secure before sending cookies.

Setting SameSite=None means that cookies are served to all users whether they are direct or referrals. The difference in setting SameSite=none and secure is in improved security for wc.org. It has nothing to do with tracking user activity across domains.

I'm thinking that if the change means the site now complies with various browsers' cookie requirements, we should see more cookies sent, ie more users, more page views, more consent banner interactions, etc. In order to test this hypothesis, I'll need to know the toggle name so that I can compile the stats in a Data Studio report.

I ran a Data Studio report for all site activity [1 December to end of Jan](url) to see what toggle names come up but I can't see anything that looks like, "SameSite" or similar. 
[Toggles DecJan.xlsx](https://github.com/wellcomecollection/wellcomecollection.org/files/7958368/Toggles.DecJan.xlsx)

**Comment by davidpmccormick** [comment]
Going to re-open this while we get data from the A/B test
