### ISSUE TITLE
Born Digital - Multiple audio files

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7596]
# Background
We are beginning to get a number of works that have multiple audio files associated with them. In these scenarios we have no way of displaying these to our users. 
Whilst the occurrences of this are currently relatively small (>50) it's currently impacting Thalidomide Oral history items which we're regularly receiving queries/enquiries about.
Related, we've also seen issues where an audio file has a poster image associated and can't display (see slack conversation: https://wellcome.slack.com/archives/C8X9YKM5X/p1642672117022700)

# Examples

- https://wellcomecollection.org/works/b4tj49m4 - This is 6 wav files and a PDF transcript. Only the first wav file is given an streaming player and the PDF is not being displayed [Not displaying all content]
- https://wellcomecollection.org/works/dmpcsthv - This is 4 wav files and 1 PDF transcript. [Not displaying all content]
- https://wellcomecollection.org/works/ve8mk3c2 - This is 1 wav file, 1 PFD transcript and a jpg poster image [Not displaying all content]
- https://wellcomecollection.org/works/trs3z9wn - This is 1 wav file and 1 PDF transcript. The file is playable in the streaming player and the PDF is available as a link underneath it as expected

# User story
As a user
I want to be able to access all content digitally
So I don't need to request / go into the building without needing to

As an organisation
We'd like all users to have access to the content we have digitised
So that our digitisation work is positively affecting the access people have to our collections

# Acceptance criteria
- All relevant audio files are available to listen online
- All additional content related to audio files are available to view online

@DominiqueMarshall / @davidpmccormick  - could you look at what a relatively light / quick win might look like for addressing this issue? We're planning to do some more work around Born Digital later in the quarter/early next quarter which might resolve this, but it would be good to know if there's anything we could implement as a quick win sooner.

**Comment by davidpmccormick** [comment]
I've made a start on displaying multiple pieces of audio in [this branch](https://github.com/wellcomecollection/wellcomecollection.org/tree/multiple-audio).

e.g.

![image](https://user-images.githubusercontent.com/1394592/151422301-08e1d35b-c673-4297-b5c9-5d96b92bc37c.png)

**Comment by DominiqueMarshall** [comment]
@davidpmccormick With the audio files, is there a way to display their individual titles or a number sequence if it's a series? I feel like for multiples there needs to be some indication of their ordering (if possible), especially if there are any cases where each file is the exact same length. Examples of what I mean below: 

Files numbered:
![Screenshot 2022-01-31 at 08 59 15](https://user-images.githubusercontent.com/60890140/151765304-aca4eb3a-265c-462a-a3e4-73f53d33cd87.jpg)

Files numbered + named:
![Screenshot 2022-01-31 at 08 59 25](https://user-images.githubusercontent.com/60890140/151765329-c4494ae2-5910-4fe2-a24b-6785b088dae2.jpg)

Same as above (but different player styling):
![Screenshot 2022-01-31 at 08 59 33](https://user-images.githubusercontent.com/60890140/151765344-ac72ef39-d0e5-4ff7-8ddf-7f5d89b73c02.jpg)

**Comment by davidpmccormick** [comment]
@DominiqueMarshall at present we're using the browser's [native `<audio>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) to render these files and it doesn't look like that has a way to include a title within the chrome of the element itself. To do so, we'd need to import or write an audio player. I guess we'll want to do this at some point, but not sure if it makes sense for this round?

At present we can add titles before/after the element. And we can certainly add sequence numbers. Which gets us to something like this

![image](https://user-images.githubusercontent.com/1394592/151815384-1e2b58a0-8c1d-489e-bc0d-de6ddc141b54.png)

What do you think?

**Comment by DominiqueMarshall** [comment]
Aah ok that makes sense. Yeah for this round the sequence numbers are good, not so sure about the repeated title anymore as it does look like overkill. Let's scratch that and keep the numbers for now.

**Comment by davidpmccormick** [comment]
For the first item in the list above (https://wellcomecollection.org/works/b4tj49m4), I can see the six parts of audio in the manifest so can render them on the page. But I'm not seeing the pdf transcript in the manifest – to display these, we look for a `resource['@type']` equal to `oa:Annotation`. I can't see that or anything that looks promising/related: 
https://iiif.wellcomecollection.org/presentation/v2/b2248887x

The second item (https://wellcomecollection.org/works/dmpcsthv) only appears to have one audio element in [the manifest](https://iiif.wellcomecollection.org/presentation/v2/b22488522), so I _think_ it is displaying everything it can correctly currently (even though the metadata mentions '4 encoded audio files'). Definitely seems like there's content missing though since the single 30 minute audio file there currently is cut off mid-conversation.

The third item (https://wellcomecollection.org/works/ve8mk3c2) does have a thumbnail associated with the audio. These thumbnails are attached to the individual piece of audio, but it looks like _all_ pieces of audio (at least of the ones that I've looked at) have a [thumbnail of a placeholder speaker icon](https://iiif.wellcomecollection.org/thumb/b22488522) if there isn't something else overriding it. I imagine we only want to display the thumbnail if it isn't going to be that placeholder image?

**Comment by cbowskill** [comment]
@davidpmccormick on your third point, I'd agree, we should only display the thumbnail if it isn't a placeholder image. It would be good to know if it's possible for an item to have multiple audio files and a unique thumbnail image for each of those audio files

**Comment by davidpmccormick** [comment]
I think from a data perspective a single work _could_ have multiple audio files each with a unique image.

A complicating factor seems to be that lots of different thumbnail image urls resolve to the placeholder image. For example each of these

https://iiif.wellcomecollection.org/thumb/b17276688
https://iiif.wellcomecollection.org/thumb/b22488522
https://iiif.wellcomecollection.org/thumb/b2248887x
https://iiif.wellcomecollection.org/thumb/b28560607
https://iiif.wellcomecollection.org/thumb/b17271939
https://iiif.wellcomecollection.org/thumb/b20110121


ends up displaying this https://iiif.wellcomecollection.org/posters/audioplaceholder.png

So I'm wondering how we'll be able to establish whether or not we want to show the image.

**Comment by aray-wellcome** [comment]
@davidpmccormick 

For https://wellcomecollection.org/works/dmpcsthv you're right, it was missing it's multiple audio in the IIIF manifest because it used to be a 1 audio file item but we re-ingested to it with multiple files. I just re-ran the IIIF manifest builder for it and all 4 wav files are present in the manifest now. But weirdly, the PDF has gone from the IIIF manifest, just like https://wellcomecollection.org/works/b4tj49m4 isn't showing it. I think this is something that @tomcrane might have to look at for us. I will put this in the #digirati channel as well. 

And agreed about the thumbnail, only show it if it's something interesting, not the placeholder.

**Comment by HarkiranDhindsa** [comment]
Agreeing with @aray-wellcome above. CI re-catalogued these titles so that multiple files are now attached to one item level record. 
For most items we won't have a thumbnail image, but we require the function to display it when we do ingest an accompanying poster image. 
Looking at the above styles, this looks the most user friendly to me:
![image](https://user-images.githubusercontent.com/61455508/151961846-f843343a-3a6b-4ea8-8f27-c5ccea44237d.png)

**Comment by tomcrane** [comment]
Hi all,

I think at least part of the problem is the limits of the pseudo-IIIF we were using for AV. This "IxIF" model was a stopgap to do just enough to describe the simple AV. It can't describe some of these more complex arrangements, such as 6 individual MP3s but all transcribed in one PDF.

For example:
https://iiif.wellcomecollection.org/presentation/v2/b2248887x

The IIIF Presentation 3 version of this manifest is able to assign the PDF to the manifest itself rather than one of its canvases:

https://iiif.wellcomecollection.org/presentation/b2248887x (canonically, or https://iiif.wellcomecollection.org/presentation/v3/b2248887x for explicit version in path).

I know this was something for later, but would it be possible to start using the v3 IIIF for AV? Then we don't need to try to retrofit more complex structures into what was already invalid v2 IIIF. I appreciate that it's probably not a trivial thing to ask as other things on the page will be coming from the v2 model, but at least we have the model in IIIF v3 to express these variations and can tweak how we transform the METS layout.

For the thumbnails - yes, looks like the use case is different. When it was the UV, it was important for the Manifest to give the player something to show in the play area. But for providing as `<audio />` elements this goes away. The required change here would be to only include the image in the Manifest if it's a real image and not fake it with the placeholder. In that example the `placeholderCanvas` property would be absent from the JSON in this case.

More generally, I think there is some modelling work to do - this was very much a first pass. For example, in the METS the PDF transcript might be associated with the first Audio file, but if there are multiple files and only the first has a PDF, we assume, just based on observed practice, that the PDF is a transcript of all the files.  What if that is not always true?

As more variants turn up, we should revisit the IIIF v3 that the DDS/iiif-builder is constructing from the METS, to make sure that the IIIF contains the information you need to construct the correct UI. For example:

Multiple AV files each with their own transcript
Multiple AV files each with their own poster image
Multiple AV files each with their own transcript but one Poster image for the work

... and probably many more.

**Comment by davidpmccormick** [comment]
Thanks @tomcrane – I'll take a look and see what it would take to get v3 for audio into shape.

With the `placeholderCanvas`, that would be one-per-manifest, is that right? Unlike one-per-media-sequence that we have in our current IIIF version? I imagine this would be ok @aray-wellcome @HarkiranDhindsa ? Or could there be instances where a work had multiple audio parts, each of which had a unique image associated?

**Comment by HarkiranDhindsa** [comment]
We haven't encountered any examples so far where a unique image is associated with each of the multiple audio parts.

**Comment by HarkiranDhindsa** [comment]
It's a question of how flexible do we want the structures to be if we do encounter such a scenario in the future.

**Comment by aray-wellcome** [comment]
This ticket has definitely grown bigger than we thought it would so I hope this isn't piling on but we thought it was important to bring up. 

@HarkiranDhindsa and I have been talking over audio stuff again to see if there was anything else we might've forgotten in all of this, especially after Tom mentioned we'd have to move to IIIF 3. We did remember that while born digital audio can possibly be handled as it is above in the examples, that digitised audio with multiple files will need to have structural metadata displayed alongside the player. We can add this structural metadata in Goobi and it it is written to the METS and then to the IIIF manifest. We have an example of this in this IIIF manifest for something we did in staging last year. https://iiif-stage.wellcomecollection.org/presentation/b2923721x (Just FYI, we had to test this audio under a different bnumber than it actually belongs to at the time)

You can see the Tape 1/Side 1 label in the IIIF manifest:
![image](https://user-images.githubusercontent.com/49983203/152133234-6383538f-a5b5-439e-87d8-5295278a3947.png)

We would need that displayed somewhere on the player or near it for each audio file for digitised items. Born digital audio wouldn't have these structural metadata labels.

**Comment by davidpmccormick** [comment]
Multiple audio parts are now rendering. Tracking the other parts of this ticket in #7663
