### ISSUE TITLE
Better error messaging for patron types that don't allow requesting

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7645]
# What is it and who's it for?

When a patron type that doesn't have the ability to request (e.g. P29) the error message that displays is very generic and not particularly helpful. It could be interpreted as a technical error as opposed to an issue with the account.

We need to update the error messaging to be more useful in these scenarios.

@DominiqueMarshall could you propose some wording? I think it still needs to be fairly generic to cover a number of account scenarios, but in essence a CTA to speak to library enquiries. Alternatively, we could state something along the lines of 'There's been an error. Please try again, if this doesn't work, please contact library enquiries'

<img width="719" alt="image" src="https://user-images.githubusercontent.com/91600241/153367857-bcda94f8-74d1-4790-b4a1-4af6cbd47276.png">

**Comment by DominiqueMarshall** [comment]
"There was a problem processing this request. Please try again. If the problem persists, please contact library enquiries for assistance."

**Comment by cbowskill** [comment]
@DominiqueMarshall  - Speaking to Alex I think we can make this more specific (e.g. know when it's a P29/temp account). therefore the message can be more explicit about not having a full account / being able to request. Maybe something along the lines: "You're unable to request items. Please contact library enquiries to upgrade your account"

**Comment by DominiqueMarshall** [comment]
"Your account needs to be upgraded before you can make requests. Please contact library enquiries for assistance"

**Comment by jamieparkinson** [comment]
If you [place a hold request](https://sandbox.iii.com/iii/sierra-api/swagger/index.html#!/patrons/Place_a_new_hold_request_post_31) in Sierra while you have a `patronType` of `29` (self registered), then currently that request is denied with an HTTP 500 containing the following:

```json
{
  "code": 132,
  "specificCode": 2,
  "httpStatus": 500,
  "name": "XCirc error",
  "description": "XCirc error : You may not make requests.  Please consult Enquiry Desk staff for help."
}
```

We don't currently handle this case, and so we return a non-specific error from the requests API. Our current handling for errors from Sierra can be found in [SierraRequestsService.scala](https://github.com/wellcomecollection/catalogue-api/blob/97062bf53cef265d14b51a9230b47ead6fa7b959/requests/src/main/scala/weco/api/requests/services/SierraRequestsService.scala#L39-L73).

We need to add a new case to the sealed trait called [HoldRejected](https://github.com/wellcomecollection/catalogue-api/blob/9935d5ddc3b8cc896cf46a9b6bedc2034151628a/requests/src/main/scala/weco/api/requests/models/HoldResponse.scala#L16) for when a self-reg user encounters this error, and associate it with the error message in @DominiqueMarshall's comment above. 

Here is a rough shape of the main pieces of this work:

- Add the new case to `HoldRejected`
- In the pattern match in `SierraRequestsService`, add a new branch for this specific error. Although the `code` and `specificCode` already exist in one of the branches, the message here is different (the comment should be updated to reflect this too).
  You could choose to match on the full error message, or you could use a [pattern guard](https://docs.scala-lang.org/tour/pattern-matching.html#pattern-guards) to say something like `if description.includes("You may not make requests")`.
- We should make sure that the user is self-reg before we return our new error - we don't know that this error won't occur for other reasons. If they aren't, we can return an `UnknownReason`.
  Annoyingly, our Sierra API wrapper doesn't provide functionality for this, so we need to add it to [SierraSource](https://github.com/wellcomecollection/scala-libs/blob/main/sierra/src/main/scala/weco/sierra/http/SierraSource.scala) in the scala-libs repo. 
  The existing method, [`lookupPatronExpirationDate`](https://github.com/wellcomecollection/scala-libs/blob/main/sierra/src/main/scala/weco/sierra/http/SierraSource.scala#L172-L195), is a useful example here for reading the patron record. Let's have our new method return the `patronType` as an `Int` directly, rather than introducing yet another abstraction. As well as adding some tests, the PR in scala-libs will need a [release note](https://github.com/wellcomecollection/scala-libs#release-process).
- Once the scala-libs PR is merged, weco-bot will automatically open a PR to bump the scala-libs version on the catalogue-api repo. It's a non-breaking change, so you should be fine to merge that and continue
- Where were we? In the new branch for the error, we need to call our new `patronType`-getting method and see whether it's `29`, in which case we can return our new `HoldRejected` case.
  There's already a method called `checkIfUserCanMakeRequests`, but if it were to check for patron expiry (as it currently does) and patronType then there will always be 1 unnecessary request made for each case where it's used. Hmmm.
- All we need to do now is to create the appropriate response for our new error type. That's in a trait called, uh, [`CreateRequest`](https://github.com/wellcomecollection/catalogue-api/blob/97062bf53cef265d14b51a9230b47ead6fa7b959/requests/src/main/scala/weco/api/requests/responses/CreateRequest.scala#L56).

**Comment by pollecuttn** [comment]
@melanierogan As this is in Done I presume this issue should be closed?
