### ISSUE TITLE
Don't 404 when looking at the ART/WIT/2 archive / yvqhmapu

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7725]
This page loads briefly, then gets replaced by a 404: https://wellcomecollection.org/works/yvqhmapu

There is something here (you can see [a Catalogue API response](https://api.wellcomecollection.org/catalogue/v2/works/yvqhmapu?include=identifiers,items,holdings,subjects,genres,contributors,production,languages,notes,images,parts,partOf,precededBy,succeededBy)), so something is going bang on the page.

**Comment by jamieparkinson** [comment]
This is caused by the IIIF manifest's mediaSequences element not having an `@id`, `format` or `width` 

See https://github.com/wellcomecollection/wellcomecollection.org/blob/58c7198d06bb46045b9fff08b4fed8ff8c737e1f/catalogue/webapp/utils/iiif.ts#L203-L208

and

https://iiif.wellcomecollection.org/presentation/v2/b29696562

That's as far as I've got, feel like the issue is with the manifest here...

**Comment by alexwlchan** [comment]
This seems to be fixed now.
