### ISSUE TITLE
Archives: Add hotjar to archives pages

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#7909]

**Comment by taceybadgerbrook** [comment]
@alicerichmond @davidpmccormick I had a stroke of genius looking at Hotjar. The reason Hotjar can't seem to produce a generic heatmap for archive trees is because each tree has a different address. Sure, there are lots of users but they are using different trees. 

I think the only thing for this is for Alice to examine some of the longer [recordings of users who visited pages containing /works/](https://insights.hotjar.com/sites/3858/workspaces/13489/playbacks/list?filters=%7B%22AND%22:%5B%7B%22DAYS_AGO%22:%7B%22created%22:30%7D%7D,%7B%22CONTAINS%22:%7B%22all_page_paths%22:%22%2Fworks%2F%22%7D%7D%5D%7D) and see how they use the tree. 

In the meantime, I'll keep checking on Event Category = ArchiveTree. So far we've had 0 events.

**Comment by taceybadgerbrook** [comment]
I think it's fair to say producing a heatmap across archives is not possible and we should turn off the tracking.

**Comment by alicerichmond** [comment]
I thought that hotjar would be tracking anything that had the "Trigger" on rather than the tree address? The reason for using hotjar is for quant data rather than qual data. Without the numbers there isnt value in gathering the data due to the recordings not really being the right research technique.

**Comment by taceybadgerbrook** [comment]
I think the issue is with the way that Hotjar produces heatmaps. 

If you look at the heatmaps, there are specific pages listed. These are compiled from recordings of individual users on the specific pages and taking snapshots of clicks, scrolls, etc. I don't think Hotjar has triggers. On a very basic level, compiling one heatmap for different-sized pages would be tricky.
