### ISSUE TITLE
Conversation around what dev work and data is needed for Digital Guides

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8014]
Digital guides being a prismic type that can reference exhibition (for the title, blurb, description and intro to gallery). Mel to check how linking content from types in prismic works. 

Could the four kinds of digital guides be referenced in one overall Digital Guides type (i.e. so we don’t have 4 types of digital guides).

The 4 kinds of guides roughly cover categories of ‘watch’ and ‘listen’.

The embedded audio player would need to have speed control. Mel to check what we have for this currently.

Can exhibition stops exist as part of the Digital Guides new type. Side note: A stop would be something that has been represented by QR codes previously. But ultimately is a part of the exhibition that you’d stop and look at/listen to.

The stops for an exhibition would all have to exist on one page, so that it is screen reader friendly.

Mel to check we can add sections Digital type in prismic i.e. can you add stops, or does the document have to pre-populated by different stops that need to be filled out or deleted in edit mode of a prismic document.

Can we somehow store the preference of the last ‘stop’ in a Digital Guide so that if a user scanned a qr code whilst in the gallery and using the guide it loads it in that category i.e. I’m looking at BSL Digital Guide, I see a barcode in the gallery, scan it and it loads that ‘stop’ in BSL category without me having to choose from the 4 categories all over.

How can we upload or batch upload digital guide content e.g. audio files, bsl videos. How does this work currently, is it all uploaded through prismic media library? S3 bucket?

How can we pull the existing image we need for an Exhibition or Digital Guide from the catalogue api? Can we map catalogue id to something human readable that prismic can refer to

Question i just thought of after the meeting: where do we see this living url wise? digitalguides.wellcomecollection.org, or www.wellcomecollection.org/digitalguides

Can we get a bit more info on the different kinds of user levels on prismic, so that we could have people who can just add content to a Digital Guides type but never publish. They could ‘tag’ the document for editorial approval or checking in some way.

**Comment by alicerichmond** [comment]
I learned some things this week that might be useful to consider when we are thinking about the data model:

- The tours are not just going to be for galleries, so when we title the data model, it makes more sense to name it something like "venue space" rather than Exhibition
- Bulk uploads and prepopulated templates would be marvellous for the media content
- We will need to consider the encoding of videos/audio and provide the requirements to those who are producing the content to ensure that they export in the right format
- Pulling images from their Wellcome Collection item ID would be really helpful
