### ISSUE TITLE
Newsletter signup page erroring when you try to sign up

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8166]
**What**

Reported at https://wellcome.slack.com/archives/C8X9YKM5X/p1658141199270219

"the person who reported it said it errors if you check one of the lower tickboxes, but it errors for me every time"

**Where**

https://wellcomecollection.org/newsletter

@davidpmccormick is getting his dotdigital account re-enabled to get more info

**Comment by davidpmccormick** [comment]
What I've learned so far:

I think the signup flow still works for all newsletters insofar as you can select any/all of them, receive a verification email and when clicking that email be signed up to the appropriate list(s).

The form on the `/newsletter` page doesn't use the [dotdigital API for adding contacts to address books](https://developer.dotdigital.com/reference/add-contact-to-address-book), but uses the form action to post (i.e. just html, no JS).

The issue seems to be that after doing this post, we're redirected to the `returnURL` we've specified (the same page, `/newsletter`) and dotdigital is appending a `?result=error` query string which we interpret as a reason to show you the error messaging on the page.

I can't see a way to determine _why_ that query string is being added, instead of `?result=success` which is what we expect after successful form actions.

Using the API would probably give us more control over this and perhaps an insight into what, if anything, _is_ going wrong under certain conditions. But it feels like it would be a chunk of upfront work for not a lot of benefit. In my mind, figuring out a way to prevent the error messaging being displayed under circumstances where there hasn't been (what we would consider) an error and sticking with the current implementation seems preferable.

**Comment by alexwlchan** [comment]
This seems to be working for me now, weird. I'm going to close it for now, we can reopen if the problem reappears.
