### ISSUE TITLE
Review the copy for email verification

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8178]
Users going through the new sign-up flow will have to verify their email address, which takes them to this page:

<img width="1144" alt="Screenshot 2022-07-19 at 18 08 52" src="https://user-images.githubusercontent.com/301220/179810520-29995aed-2587-468f-a0e4-c6b5b812293d.png">

We weren't testing the email flow in staging, so we didn't review this screen – it'll need tweaking to remove instructions to email in ID/proof of address.

**Comment by DominiqueMarshall** [comment]
Some clarification from Amelia about the 3 working days process:

"From my perspective, this line would still be relevant because we need to finalise a user’s membership and check their ID before granting them access to the closed store collections (even though they’ve ordered items) and printing a library card.  It’s really tied up with our access conditions."

**Comment by alexwlchan** [comment]
> From my perspective, this line would still be relevant because we need to finalise a user’s membership and check their ID before granting them access to the closed store collections (even though they’ve ordered items) and printing a library card. It’s really tied up with our access conditions.

Do we know what it means to "finalise" a user's membership? They can order items as soon as they verify their email (and that was true under the old system also), so the online component at least has no restrictions on item ordering.
