### ISSUE TITLE
Changes to date picker's date picked depending on when it is used

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8215]
**What**

Library Experience and Engagement colleagues would like to have a change made to when requesters can request material for based on when the request is made:

> There’s a issue where visitors ordering materials up until 10am on Sunday are able to select Monday as the date of their intended visit. However, because we are closed on Sunday there isn’t time for us to retrieve the material. This means that retrievals colleagues are scrambling on Monday AM to retrieve those items as quickly as possible, in case the visitors arrive.

**Where**

Any requestable item e.g. https://wellcomecollection.org/works/e9u63avh 

### TODO

- [x] Change the date picker such that:

Request made: | For first date of intended visit:
-- | --
Before Monday 10am | Tuesday
Monday 10.01 | Wednesday
Before Tuesday 10am | Wednesday
Tuesday 10.01 | Thursday
Before Wednesday 10am | Thursday
Thursday 10.01 | Saturday
Before Friday 10am | Saturday
Friday 10.01 | Monday
Before Saturday 10am | Monday
Saturday 10.01 - Mon 10am | Tuesday

- [x] Change the wording on the requesting modal from: 

> Item requests need to be placed by 10am the day before your visit.

to:

> Item requests need to be placed by 10am on the working day before your visit.

### Comment from @davidpmccormick 

>  I think the solution should maybe be slightly more abstract than what Simon suggested such that if a reader requests something on any day that the library is closed (i.e. not just Sundays, but other holidays), then the next available pick-up date should be the next day the library is open + 1 — basically the same as what they're suggesting but handling e.g. holidays as well as weekends

**Comment by davidpmccormick** [comment]
Based on how it makes the test fail, I think a straightforward solution to this is to add 2 days instead of 1 in the [`findNextRegularOpenDay` function if we're in the `isClosed` condition](https://github.com/wellcomecollection/wellcomecollection.org/blob/b71086802ffef24eb87855c3c85e216775f0a2d0/catalogue/webapp/utils/dates.ts#L64-L65).

I think if we did that, we should rename the function to reflect that it's a 'pick-up' date rather than an 'open' date, fix the tests, and probably write one or two more. But it doesn't look like the function is being used elsewhere so I think it would be ok.

It wouldn't deal with exceptional closed dates, but perhaps it makes sense to make this change first to help alleviate the Monday morning scrambles, then deal with the rarer exceptional closed dates in a future PR.

If I have this right, I don't think the initial change should be more than half a day to implement (but dates are thorny, and it's definitely worth someone else verifying that I've not overlooked something).

**Comment by davidpmccormick** [comment]
Thinking about it more, I don't think that'll work – a request made on a Saturday would result in a next available pick-up day of Monday. I've closed #8220
