### ISSUE TITLE
As a Stories editor, I need to choose and update relevant Stories from the archive on the Stories landing page

### ISSUE THREAD

**Issue by dannybirchall** [wellcomecollection/wellcomecollection.org#8245]
# What is it and who's it for?

Making more of the Stories homepage editable, so that Stories editors can choose stories from the archive for increased impact on the readership

# User story
As a Stories editor
I need to choose and update relevant Stories from the archive on the Stories page
So that users can find and read Stories aligned to current promotions and themes

# Implementation 

UX design plus changes to Prismic, allowing editors to group and present content thematically

## Acceptance criteria

Stories page can be edited by Stories editors

## Testing and tracking
tbc, suggest monitoring clicks on page, A/B testing?

## Measurement
overall stories traffic

## Other considerations 
Can stories be added directly and appear as cards, rather than using card content types as we do on the homepage?

**Comment by DominiqueMarshall** [comment]
Quick summary of where I'm at with this cc @dannybirchall :

- Had a catch-up with Alice W and discussed the need to find the balance between how the editorial team want to responsively resurface and curate content, while meeting the user needs of being able to discover and engage with particular topics they’re interested in. Also reviewed the existing stories topics spreadsheet to gain a better understanding of what actually exists.

- Discussed the various ways that the landing page could be sectioned, and what would be the most effective way of achieving this (e.g. formats, topics, strategy priority areas etc)

**Concluded that for the first iteration...**
As the number of different topics is so vast, we agreed to try out using the story series options as a means of surfacing content, as these links already exist in Prismic, i.e:

- guest-edited weeks
- theme weeks
- serials
- from our collections
- + have a "blank" section available where content can be proactively resurfaced manually rather than dynamically

**Next steps:** 
Explore what the design of the page could look like

**Comment by DominiqueMarshall** [comment]
Ticket is now superseded by newer tickets created after a Stories workshop with the access team: https://github.com/wellcomecollection/wellcomecollection.org/labels/epic%3A%20stories%20optimisation
