### ISSUE TITLE
Remove comics from the list of recent stories on the stories landing page/homepage

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8399]
This was an aside from Danny in the stories meeting: currently web comics and articles appear in the same list of recent things, even though they're not the same type of thing.

We should look at breaking out comics from this list, possibly in a standalone component akin to #8398?

This needs some design/UX work to decide where comics should live if not in this scrolling list, and some dev work to implement it.

**Comment by DominiqueMarshall** [comment]
UX of the Stories landing page, featuring two options for the Comics section: [Stories - Comics](https://zpl.io/YYZ5zYn)

**Version 1 of the Comics section (the first line of comic strips)** - shows the latest comic in chronological order as the website does currently.

**Version 2** - Showing the most recent series of comics, rather than the individual parts. This option is more in line with what we're aiming for with the serials - making it easier to discover past comics beyond the latest series.

I've placed them underneath the Serials section, as it feels like those are still the highest priority after the Latest articles.

I would want to aim for the second option, but happy to start with the first one initially. 

@dannybirchall - with the second option, when you click "View more comics" and hit https://wellcomecollection.org/articles, would you expect to see a filtered list of 
a) the past comic series following the same style as the landing page, or 
b) the individual parts, like how the page shows currently?

**Comment by dannybirchall** [comment]
@DominiqueMarshall I'd expect to see the former: a list of links to the index page for each series of comics, back to body squabbles.

(I think that this is part of how Stories in general should show more tendency to 'stack' things by their series, so that you can see more different things in a single view rather than a stream of related thigs)

**Comment by gestchild** [comment]
Splitting the comics out from the rest of the stories is not straightforward. The format field, which is how we distinguish comics from other story types is a linked document field and Prismic doesn't allow us to filter queries on linked document fields.

**Comment by davidpmccormick** [comment]
Could we request more items than we need and filter out the comics on the frontend? Not lovely.

**Comment by dannybirchall** [comment]
@davidpmccormick then we'd have to do that twice: once again to filter comics into their own section also?

@gestchild if we rigorously tagged comics as comics, would that enable you to filter?

**Comment by davidpmccormick** [comment]
@dannybirchall oh yep. As is the case depressingly often, I hadn't read the specifics of the ticket properly

**Comment by alexwlchan** [comment]
> The format field, which is how we distinguish comics from other story types is a linked document field and Prismic doesn't allow us to filter queries on linked document fields.

Are you sure? I wonder if I'm missing something, because I can add a predicate in `stories.tsx` and it seems to be doing the right thing:

```typescript
const articlesQueryPromise = fetchArticles(client, {
  predicates: ['[not(my.articles.format, "W7d_ghAAALWY3Ujc")]'],
});
```

**Comment by davidpmccormick** [comment]
I didn't even check, but I'll pick this up now since it seems like @alexwlchan is most likely right!

**Comment by davidpmccormick** [comment]
@dannybirchall I think it would make sense to have the comics section title/blurb content-editable, as is the case with other sections on the stories landing page. I'll work on that next, but do you have any appropriate words for me to stick in here while you wait for it to be editable in Prismic? 

![Image](https://user-images.githubusercontent.com/1394592/206441291-23898019-3e3d-4fd8-aa19-44c003fd018b.png)

**Comment by dannybirchall** [comment]
@davidpmccormick how about

Comics

Explore new perspectives on bodies, brains and health with our guest comic artists.

**Comment by davidpmccormick** [comment]
Closing as done in #8979 and #8999 behind the `storiesLandingComics` toggle.

**Comment by davidpmccormick** [comment]
Have spoken with @dannybirchall about this – we agreed:

1. the logic on stories landing page is ok as is
2. there is an editorial task to update copy on comic series promos (some have a lot, some have none, and this can make cards look bad)
3. homepage listing doesn't require updating to filter out comics
