### ISSUE TITLE
Explore nginx as a way to handle interapp routing locally

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8798]
A step two to https://github.com/wellcomecollection/wellcomecollection.org/issues/8797, this ticket will aim to explore how to handle interapp routing locally through nginx.

Apps to consider:
- catalogue
- content
- identity

**Comment by alexwlchan** [comment]
I've cannabalised my old site config, here's a starting point:

```conf
# nginx.conf

events
{
	worker_connections 1024;
}

http
{
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server
	{
		listen 80;

		location /
		{
			proxy_pass http://host.docker.internal:3000/;
			proxy_redirect http://host.docker.internal:3000/ http://$server_name/;
		}
	}
}
```

```console
$ docker run -p 5000:80 -v (pwd)/nginx.conf:/etc/nginx/nginx.conf nginx:alpine
```

If I go to http://localhost:5000, Docker will fetch whatever's running on http://localhost:3000 instead and proxy it through to me.

This doesn't have our routing rules, but it's a start.

**Comment by jamieparkinson** [comment]
2 points:
- I might consider using HAProxy instead of nginx as its config of "frontends" and "backends" is designed around this sort of use case and I have previously found it to be less of a pain
- Can we try to use docker-compose networking (ie bridge networks) instead of binding to various host ports? Exposing ports _and_ proxying them is confusing, and the docker-compose DNS magic is very nice.

**Comment by AMBacelar** [comment]
I was about to lay my head into bed but now I've thought that the easiest way to get those chunks pointing to where we want them to go, may be with adjusting the webpack filename configs, if we insert `wc-catalogue`| `wc-identity` in the beginning of the string for all webpack compiled files, that may make not just the local reverse-proxy, but maybe even the AWS load balancer easier to configure moving forward.

**Comment by AMBacelar** [comment]
After another round of exploration I've attempted modifying the webpack configuration files to append a prefix to all files generated by next on both the server and the client.

After making modifications to the webpack configuration outputs, I was able to change the names of the generated files, but I was not able to maintain the desired file structure. For sure someone more familiar with webpack configurations may have been able to get further on this aspect of the task.
[modifying webpack output files](https://webpack.js.org/configuration/output/)

But the main reason would be that I believe that I hit a roadblock due to going down a NextJs anti-pattern. There are more than just the weback files generated by next, and the initial data generated by the server functions also needs to be transformed so that the final filename has the required prefix.
The documentation and conversations in the next repository point to a feature called `zones`, and it would seem that zones are the intended way to run multiple next applications inside of one directory. And this should go up for conversation with the rest of the team due to how large a change this may end up being to the repository, potentially affecting how the application operates in production, and not just in a dev environment.

[next zones](https://nextjs.org/docs/advanced-features/multi-zones)
[next rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites)

## Bibliography
[initial conversation on running multiple next apps on one port](https://github.com/vercel/next.js/issues/257)
[official example of zones working](https://github.com/vercel/next.js/tree/canary/examples/with-zones)

**Comment by pollecuttn** [comment]
To be continued by investigating running apps locally
