### ISSUE TITLE
Identifying works pageviews for fully-digitised items

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8869]
**We want to know if the following change has improved the user experience**
Researchers are able to navigate from works pages to item views more easily

**Definition of success is**
More item page views

**We'll know if we're succeeding if we measure the following metric and this happens**
Increased percentage of total works pages for fully-digitised items / total fully-digitised item pageviews

**Comment by taceybadgerbrook** [comment]
This work has arisen from ticket #8827.

**Comment by taceybadgerbrook** [comment]
We want to be able to count how many works pages have a View button:

![image](https://user-images.githubusercontent.com/32418070/201704677-ee129ff7-a14c-42c9-9952-23662671b246.png)

**Comment by jennpb** [comment]
Just to add a bit more abstraction to this, as we might not always have a view button as the mechanism for viewing the content - we want to know the CTR from `/works` pages to `items` _only_ for those works that have attached items.

I'm not sure the main description in this issue is now relevant to the question that's being asked, so maybe we need to close this and create a new issue?

**Comment by taceybadgerbrook** [comment]
A new ticket #9590 has been opened.
