### ISSUE TITLE
In Plain Sight audio guides: tagging guide selection

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9007]
**We want to know if the following change has improved the user experience**
User experience of exhibition is enhanced by audio guides.

**Definition of success is**
Users listen to the audio guides.

**We'll know if we're succeeding if we measure the following metric and this happens**
By tagging the audio guides for QR and non-QR users, "events" for the different guides can be collected which shows users listening to different audio guides beyond the first one. 

**Definition of failure is**
Users don't listen to the audio guides.

**We'll know if we're failing if we measure the following metric and this happens**
There are few events for the audio guides beyond the first guide.

**Comment by jennpb** [comment]
Just checking, is this not showing that this is a QR hit? `usingQRcode=true`
I can see this data in GA.

`https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions?usingQRCode=true&stopId=mati-armour-8`

On desktop/direct visits (non-QR), I note that the play button doesn't trigger a change in URL, so presumably non-QR visits aren't triggering any audio plays? Would this just entail having a `usingQRcode=false` but otherwise follow the same pattern? Or is there an alternative to this where an event on all audio players should capture:
- QR or non-QR
- Play button activated
- stopID

**Comment by taceybadgerbrook** [comment]
@jennpb non-QR visits are triggering audio plays but because they don't trigger any changes in url, all play buttons activated just show up as events on the audio player homepage without any information about which stops they selected. So for all I know they all listened to stop 1 and then decided that was more than enough.

There is an event called button already in GA but this is not linked to the audio player actions.

**Comment by taceybadgerbrook** [comment]
This work is now covered by #9038
