### ISSUE TITLE
In Plain Sight audio guides: hotjar tracking

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9008]
**We want to know if the following change has improved the user experience**
User experience of exhibition is enhanced by audio guides.

**Definition of success is**
Users are engaged.

**We'll know if we're succeeding if we measure the following metric and this happens**
Hotjar tracking shows large numbers of users ~~clicking on the play buttons, mousing over text and~~ scrolling down through the guides.

**Definition of failure is**
Users are ~~distracted,~~ not engaged.

**We'll know if we're failing if we measure the following metric and this happens**
Hotjar tracking shows large numbers of users ~~clicking on the "Change guide type" or "Change exhibition" buttons, non-existent mousing over text, few play button clicks and~~ with shallow scroll depth.

**Comment by jennpb** [comment]
Just want to query the use of Hotjar for all of this. I would prefer we use Hotjar only if we've deemed alternative methods to be ineffective, just because it is more invasive, privacy-wise.

Breaking this into the multiple metrics mentioned above:

- **Buttons in header**: We can see the data for "Change guide type" and "Change exhibition" in GA using Navigation Summary/Next Page Path
- **Hover data** not going to be very useful on mobile

- **Play buttons**: For Play buttons, it seems like a play is something we'd want to track for all audio content, not just temporarily in the exhibitions. Could we add an event to the play button instead? 

That leaves **scroll depth** as the one metric that Hotjar is pretty good at.

What do you think @davidpmccormick and @gestchild

**Comment by taceybadgerbrook** [comment]
That seems fair enough. Navigating from [the IPS audio guides page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions) to another type of guide means specifying the next page path as https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau because the user then has to choose a guide type. This could also be the result of someone clicking Back but I think we cal live with this.

**Comment by taceybadgerbrook** [comment]
Play button tracking is in ticket #9007. I'll cross out everything except scrolling from the first part of this ticket.
