### ISSUE TITLE
Review and rework our current reach and engagement KPIs

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9102]
# What

Review our current reach and engagement KPIs and rework them based on what metrics GA4 makes available

# Why

So our measures of success are realistically measurable using data from GA4
So we can begin to transition from reporting on one set of metrics to the new metrics over the next few quarters

# Done when

- [ ] We have a single list of all of our current KPIs (focus on long-term indicators), in one place that's accessible to Platform + Content 
- [x] Audio and video engagement measurement agreed
- [ ] We've reviewed this with Content team for shared understanding and agreement

**Comment by taceybadgerbrook** [comment]
@jennpb I have done an audit of GA vs GA4 metrics and we can report on everything using GA4 that we report on using GA. Bounce has comparatively recently been added to GA4. The one exception is time on page (engagement time isn't quite comparable.)

I think the work that needs to be done is considering better metrics that are available in GA4. A good example are the daily/weekly/monthly active user metrics which measure the number users by the frequency of site visit. We've had steadily declining numbers of monthly returning visitors since before covid and I'd like to work with the team to address this. Return frequency metrics would be a good way to track progress.

**Comment by jennpb** [comment]
Great stuff- can you point us to where that audit is currently stored?

**Comment by taceybadgerbrook** [comment]
@jennpb Here is the link to the GA vs GA4 audit/quality assurance work:
https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/GA4%20Quality%20Assurance.xlsx?d=wc6ec5c49664d4dd59114a65e21ab80a0&csf=1&web=1&e=SebDVN

Here is a link to the spreadsheet containing GA KPIs currently used in reporting and the GA4 equivalents for purposes of communicating the transition:
https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/wc%20consolidated%20stats.xlsx?d=w00c40d2c68fd4e2cadc28720e0e7cc27&csf=1&web=1&e=Wm2pxc

**Comment by jennpb** [comment]
Full list of what we need to track: https://docs.google.com/document/d/1hTDviYfwEE7mZGVD41bQztjX2MDcnYy1oGCmbf0EUt4/edit?usp=sharing

**Comment by jennpb** [comment]
Moved to Gitbook: https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/

Given that we're in a transitional state with the Wellcome Collection strategy, I expect we'll want to tweak our reach and engagement KPIs further in FY 2023-24. For now, we have a shared reference in Gitbook.
