### ISSUE TITLE
In Plain Sight Powerpoint slide deck: navigation and device analysis

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9145]
This ticket builds on analysis in #8252 and #9038.

**Comment by taceybadgerbrook** [comment]
Slides to be added to existing Powerpoint slide deck:
Changing guide type, exhibition
1. overview slide. all changes from one guide type to another, exits from original guide type, change of exhibition
2. slide 1. but by desktop vs mobile
3. Audio: from QR code scan at stop 0 or 1: all changes from one guide type to another, exits from original guide type, change of exhibition
4. slide 3. but by desktop vs mobile
5. BSL: from QR code scan at stop 0 or 1: all changes from one guide type to another, exits from original guide type, change of exhibition
6. slide 5. but by desktop vs mobile
7. Captions and transcripts: from QR code scan at stop 0 or 1: all changes from one guide type to another, exits from original guide type, change of exhibition
8. slide 7. but by desktop vs mobile

**Comment by taceybadgerbrook** [comment]
Page design
9. Audio: Hotjar analysis of homepage by desktop vs mobile
10. Captions and transcripts: Hotjar analysis of homepage by desktop vs mobile

@davidpmccormick could we please have the Hotjar tracking for Audio turned off and tracking for Captions and transcripts turned on?

**Comment by taceybadgerbrook** [comment]
Overall QR code usage
13. Audio: by device, exit rate
14. BSL: by device, exit rate
15. Captions and transcripts: by device, exit rate

**Comment by davidpmccormick** [comment]
The hotjar heatmap as it is currently set up is tracking _all_ pages that start with the In Plain Sight url (https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau). In order to check scroll depth on the 'Captions & Transcripts' page, you'd have to add a filter like this

![image](https://user-images.githubusercontent.com/1394592/214292823-520e0aa1-9958-4a9c-bc36-9817612edc36.png)

This _does_ mean that the analysis you've already done hasn't been specific to the audio page though – in order to check that specific page, you'd have to follow the same process, adding a filter with the string `audio-without-descriptions`.

**Comment by jennpb** [comment]
> @jennpb could you review the slides I intend to add to the existing Powerpoint slide presentation? The slide deck will be uploaded to Sharepoint.

Looks like it covers all the data points, but you can use your best judgement with the presentation and sequence of the slides - in addition to any interesting insights you want to point out. Thanks!

**Comment by taceybadgerbrook** [comment]
@jennpb PowerPoint slides now finished. 
[In Plain Sight digital guides usage analysis v2.pptx](https://github.com/wellcomecollection/wellcomecollection.org/files/10545761/In.Plain.Sight.digital.guides.usage.analysis.v2.pptx)

**Comment by jennpb** [comment]
@taceybadgerbrook I left a few comments on the slidedeck but I realised I need access to the pptx on Sharepoint (rather than a copy uploaded to Github) in order for you to see them. Can you pop the link in here so I can access it?

Next step is to look at this data as a team and work out what we'll do next. I have an idea for a working session, I'll get it in the diary.

**Comment by jennpb** [comment]
Thanks @taceybadgerbrook 

Will await some qualitative insight from the research with Touretteshero and we can run through this and make a plan.
