### ISSUE TITLE
Exhibition guide preference

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#9198]
Hello lovely wellcome people, someone shared one of your stories with me at work and it made me have a poke around and i noticed what i *think* is a bug with exhibition guides, but hey, it could also be a feature ;)

**What**
It looks like we now only remember a chosen guide preference when someone scans/arrives from a qr code url. At one point, the preference cookie would remember and serve your preferred guide type on any exhibition guide, even if you didn't come from a qr code url.

**Where**
I think this means we just serve the preferred guide type for qr codes:
https://github.com/wellcomecollection/wellcomecollection.org/blob/45b0c2423860b5036c0a23713470edeedf517818/content/webapp/pages/guides/exhibitions/%5Bid%5D/%5Btype%5D.tsx#L104

**Comment by alexwlchan** [comment]
Hi Mel! Thanks for getting in touch. Hope the new job is going well!

This is intentional. We made the redirections quite a bit more conservative after we discovered some… confusing aspects to the behaviour. In particular, you could get the following sequence of events:

1. A user goes to an exhibition guide overview page `/guides/exhibitions/[id]`
2. They click to select a particular exhibition guide, say `/guides/exhibitions/[id]/audio`. This sets a preference cookie telling us the user wants audio guides.
3. They click the "Back" button in their browser because they want to see the page they were just looking at. This takes them to `/guides/exhibitions/[id]` … where we redirect them back to the page they were just looking at.

I went and tracked down the patch where we made this change – it was reviewed by somebody with a familiar name. 😉 https://github.com/wellcomecollection/wellcomecollection.org/pull/8653

Although I’m going to leave the behaviour the same, I’m not sure that rationale is actually documented anywhere, so I’m going to update the comment above that line before I close this ticket.
