### ISSUE TITLE
Go through UA events to decide which we want to reproduce in GTM

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9201]
# What

- Go through UA events to decide which ones we need as equivalents in GTM/GA4.
- Check what helps with that in GA4: do we need to add, or does GA4 already give us this?

# Why

- To eliminate unnecessary tracking events from our codebase
- To agree what we need to track at a component level

# Background

[UA events cheatsheet](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA%20annotated%20event%20tracker%20cheatsheet.xlsx?d=w3da23ec90ea449569b0520e035bda462&csf=1&web=1&e=QVoZU1) (Excel/Sharepoint link)

[Quality assurance: comparing UA and GA4](https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EUlc7MZNZtVNkRSmXiGrgKABmO5Az-ROgs8Jnn5uG9n80A?e=L1grCW) (Excel/Sharepoint link)

[Events used in UA and GA4](https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EUlc7MZNZtVNkRSmXiGrgKABmO5Az-ROgs8Jnn5uG9n80A?e=L1grCW) (Excel/Sharepoint link)

## Done when
- [x] Full component review (with keep, remove, etc decisions documented)
- [x] Create a list of all events to remove now
- [x] Create a list of all events we want to create in GA4

Part of epic #9101

**Comment by jennpb** [comment]
7 Feb update:
- We matched works, items and search tracking to the UX architecture audit; indicated which event tags are no longer needed, which need to be refashioned in GTM, and noted any other areas for investigation.

Next steps:
- Dom to review What's On, digital guides, stories (priority) for component usage
- Investigate to what extent the Explorer reports give us the ability to track clicks without adding event tracking tags
- Confirm how many Explorer reports we're allowed

**Comment by taceybadgerbrook** [comment]
@jennpb I looked into the events that show up as conversions today. I think this work was leftover from months ago when I was investigating events. I have turned off conversions for video_complete, video_empathy_in_an_age_of_division and video_progress.

video_empathy_in_an_age_of_division is a custom event I set up. It's not possible to delete custom events so I have renamed this, "test" so that it can be reused. If you look at Admin/Events and set the date period from tomorrow onwards, the event only "test" will appear.
