### ISSUE TITLE
Can we have ‘views’ of this GA4 property like we could in UA?

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9204]
With regard to public vs internal staff use to help us differentiate between them.

**Comment by taceybadgerbrook** [comment]
@jennpb There are a lot of GA views that have been set up but we always use B. Did we ever use A or C?

<img width="650" alt="image" src="https://user-images.githubusercontent.com/32418070/218760002-81a98ad2-6c6b-4600-b306-e2430ff9fb18.png">

**Comment by jennpb** [comment]
I used to look at C when I wanted to focus in on catalogue and search activity, but that would have been on the wellcomelibrary.org GA account, as staff use is more intensive. When these were set up by a former UXer (DRM), he was making the views consistent across all Wellcome properties: `ac.uk`, `wellcomeimages`, `wellcomecollection`, `wellcomelibrary` etc. 
A = made no distinction
B = external IPs and internal Wifi
C = internal IPs

All of the others were never used.

**Comment by taceybadgerbrook** [comment]
@jennpb It sounds as though C was never used for wellcomecollection.org. It's easy enough to exclude internal users from the GA4 property. Are you happy for me to do this?

**Comment by jennpb** [comment]
We shouldn't do anything that permanently excludes internal users. 

Ideally we'd:
- Have the equivalent of UA's B view; that is, external users + wifi - this would allow us to transition to GA4 on the same user criteria
- Have a way of filtering to internal users, in case we need to do further in depth analysis of staff use vs public use.

If there's another way of doing those two things, we should consider the options.

**Question: in your GA4 vs UA analysis, did you set up anything in GA4 so that it met the same criteria as UA view B? Or were you comparing what's effectively 'All users' in GA4 to UA view B?**



using the equivalent of UA's B view for ongoing reporting

**Comment by taceybadgerbrook** [comment]
@jennpb I set up GA4 the same as GA view B.

**Comment by taceybadgerbrook** [comment]
## Filtering out internal usage by IP address ##
(see Data streams/Configure tag settings/Settings/Show more/Define internal traffic)

215 users: 195.143.129.132
Digirati Glasgow: 62.254.125.26, 62.254.125.32
Digirati London: 46.102.195.182, 46.102.195.32
