### ISSUE TITLE
Back to results doesn't work in staging + prod

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9452]
**What**
[See Slack convo](https://wellcome.slack.com/archives/C8X9YKM5X/p1679392203867129)
"Back to results" on work pages always displays as "Back to search" (without the previously selected filters/pagination/any query element) as it can't detect a link in the Search Context.
It works locally, so I wonder if it has to do with redirections?

**Where**
1. https://wellcomecollection.org/search/works
2. Enter keyword, change page, add filters
3. Click on a work item
4. Observe "Back to search" hasn't retained any filtering, sorting or keywords and defaults to the main search page.

**Comment by pollecuttn** [comment]
@AMBacelar as I'm off next week I won't be able to keep an eye on this. When it's been deployed please let Jenn know it's been fixed.

**Comment by alexwlchan** [comment]
I don't think this is redirection related – all the redirection logic lives in CloudFront, and you can rule out CloudFront as a culprit by making requests directly to the EC2 load balancer at http://prod-1800364202.eu-west-1.elb.amazonaws.com/search/works?query=fish

```mermaid
graph LR
    C["CloudFront (inc. redirections)"] --> ALB[EC2 Load Balancer]
    ALB --> ECS["ECS service (aka app running in Docker)"]
```

That's still dropping the search context, so the issue is happening pre-CloudFront/pre-redirections.

**Comment by alexwlchan** [comment]
Fixed!
