### ISSUE TITLE
Improving quality of CTR from /works to /item pages

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9590]
**As a** researcher

**I want** to discover more of the collection

**So that** I can conduct research more effectively

We will know we are enabling wider usage of our collections if the CTR of users viewing digitised items after viewing /works pages increases.

Currently, the CTR from /works pages viewed to item page views includes /works pages which do not contain links to digitised items. This means that if the CTR decreases, it could be because users are viewing more /works pages without links to digitised items.

Can we send data to Elasticsearch identifying /works pages for digitised items?

**Comment by taceybadgerbrook** [comment]
This ticket follows on from #8869

**Comment by gestchild** [comment]
I have a couple of questions @taceybadgerbrook:

"We will know we are enabling wider usage of our collections if the CTR of users viewing digitised items after viewing /works pages increases."

- Do we need to know the click through rate or can this just be measured by an increase in item page views?

If we do still want to measure the click through rate from works to item pages, just identifying works with digitised items will improve the problem you've identified above but won't solve it completely because not all works with digitised items have an item page we link to. Some have external links to the resource, audio and video items are available on the work page itself and some items are restricted so we won't show a link.

- I think what we want to know is when the work has digitised items that are either a iiif-presentation or iiif-image location (meaning we display them), but are not audio, video or restricted. Does that sound right to you?

**Comment by taceybadgerbrook** [comment]
@gestchild 

> - Do we need to know the click through rate or can this just be measured by an increase in item page views?

We don't need an event to calculate the click through rate. I would do this in Python using counts of tagged works pages and item page views.

**Comment by taceybadgerbrook** [comment]
@gestchild 

>  not all works with digitised items have an item page we link to. Some have external links to the resource, audio and video items are available on the work page itself and some items are restricted so we won't show a link.

Hmmm. Could we tag them all regardless?

**Comment by taceybadgerbrook** [comment]
@gestchild 

> - I think what we want to know is when the work has digitised items that are either a iiif-presentation or iiif-image location (meaning we display them), but are not audio, video or restricted. Does that sound right to you?

I think this is too fine-grained. We want to know whether users who view works pages click to view/play when there is a link/button on the page regardless of their type.

**Comment by gestchild** [comment]
@taceybadgerbrook 

> We don't need an event to calculate the click through rate. I would do this in Python using counts of tagged works pages and item page views.

I was really questioning why we need CTR at all. If what we want to know is that, "we are enabling wider usage of our collections" can't that be determined by an increase in views of item pages and plays of audio and video?

**Comment by gestchild** [comment]
@taceybadgerbrook 

> Hmmm. Could we tag them all regardless?

We can, that is actually easier, but then it'll include works that don't link through to item pages, which I thought was the original problem we were trying to solve.

**Comment by gestchild** [comment]
@taceybadgerbrook 

> I think this is too fine-grained. We want to know whether users who view works pages click to view/play when there is a link/button on the page regardless of their type.

I think we're saying the same thing. The conditions I outlined are what determine whether there is a link to an item page.

It also sounds like you need to know whether the audio/video is played, which is something we don't track in Segment only GA at the moment.

**Comment by taceybadgerbrook** [comment]
> I was really questioning why we need CTR at all. If what we want to know is that, "we are enabling wider usage of our collections" can't that be determined by an increase in views of item pages and plays of audio and video?

@jennpb This is a good question. If users can only view/play digitised items by locating a works page and then clicking to view/play, do we really need a CTR?

**Comment by jennpb** [comment]
Probably not.

My interest in CTR is generally about the design of a page, rather than judging overall use. As you say, the video and audio are embedded so there isn't a click through as such.

Where click-throughs make a difference is when we get to the point of changing calls to action on the page (buttons, links, etc). But it sounds like this is a moot point with audio and video.

**Comment by gestchild** [comment]
Can I close this then, as I don't think we need to do anything.

When we get to the point of changing calls to action we could run an a/b test, rather than compare changes to historical data.
