### ISSUE TITLE
Understand current user behaviour and usage of exhibitions and visual stories

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9759]
# What do we want to know?

We want to understand what user interaction with exhibitions and visual stories currently looks like. What can GA tell us?

- How are people getting to the content we're interested in? (traffic acquisition, search terms, etc)
- Are people finding the links to visual stories from exhibition pages? (Page views of visual stories as a % of page views of the exhibition it's related to?)
- What devices are prevalent?
- Return vs New users of the content?

We're interested in the following content:
- any `/exhibition`
- `/access`
and specific Visual stories
- PDF outbound from In Plain Sight
- PDF outbound from Milk
- Being human visual story https://wellcomecollection.org/pages/Xeo6OREAAB8A3wTA 

# What research technique is required?
Google Analytics - usage analysis

# Outputs
A slidedeck or GA4 Exploration

# Deadline
Friday 12 May

**Comment by taceybadgerbrook** [comment]
<img width="357" alt="image" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/338b95b5-19f9-4474-afa8-7a9049cc346e">

**Comment by taceybadgerbrook** [comment]
Search Console reports only 5 users landed on the Visual Stories page after submitting a Google search. The rest of the users who arrived at the Visual Stories page did so after landing on other pages. Here are the queries submitted by those 5 users:

<img width="761" alt="image" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/ab8f4028-ab0d-4638-928d-71f13faaf033">

**Comment by taceybadgerbrook** [comment]
Looking at the page path analysis for the 63 users who viewed the Visual Story page, 21% come from Being Human and 14% come from the Accessibility page but the rest seem to view exhibition pages before looking at visiting info/opening times before arriving at the page. While it appears that users get to the page in the end, this is only because this graph was produced using the Visual Story page as an end point.

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/7a77ef50-8d0b-41dd-84d7-15718381ed7c)

If we look at the [paths taken by the 538,000 users](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/DHjUWZegTXysSpNcoykqPQ) during 1 April - 1 May, we see only 5 users take the most direct route of home/visit-us/accessibility/visual story:

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/a9ae6f69-e850-44f6-a6f6-9d174f9f724b)

**Comment by jennpb** [comment]
Following on from the meeting on 15 May, we talked about how else we might find information about behaviour of returning visitors.

- What more can we learn about returning users and page visits? 
- Can we use path exploration with a returning users segment for a fuller picture?

**Comment by taceybadgerbrook** [comment]
Here is what a backwards Path exploration to the Being Human visual story page looks like for the period 20/10/22 - 10/5/23:

![Being human vs path](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/86423d73-ba76-437e-aefd-0b7509463e36)

Most users came to the Visual Story page from the Being Human exhibition page. Most of those users came from the Being Human captions page (https://wellcomecollection.org/pages/X3MY5hEAACQAoWCy)

**Comment by jennpb** [comment]
**Return users:** 
Given the context of visual stories, is there anything we can learn about return visitors specifically on the Being Human visual story? Can we identify whether return visitors return to that page? 

**Path exploration:**
I'm a bit confused by this because the graphic isn't interactive and doesn't have the page names. Can you link to the exploration so we can delve a bit further? Screenshots of the path exploration are definitely not very legible.

But I can't see where there are links between the Being Human captions page and the Being Human visual story, so I'm not sure what you mean by this 

> Most users came to the Visual Story page from the Being Human exhibition page. Most of those users came from the Being Human captions page (https://wellcomecollection.org/pages/X3MY5hEAACQAoWCy)

Is it possible that the path exploration is not counting a return to previous page as a step?

Here's what I mean

`Exhibition > Visual story` - this is a legit path because there's a link from one to the other (but not back again!)

`Exhibition > Visual story > Captions` - this doesn't exist as a path because there are no links 

Should we assume that what's actually happening is:

`Exhibition > Visual story > back to Exhibition > Captions` and the exploration doesn't count that second Exhibition page view as a step?



Is the path exploration accounting for users that return to

**Comment by taceybadgerbrook** [comment]
> Path exploration:
> I'm a bit confused by this because the graphic isn't interactive and doesn't have the page names. Can you link to the exploration so we can delve a bit further? Screenshots of the path exploration are definitely not very legible.

[Here's the link to the path exploration.](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/cIlniX8rRJucWkEPO32K4Q). If you make a copy of the Explore report it's in (Engagement, owner: Tacey), you can have a play around with it. The path exploration in the link will look different from the one pasted into the comment above because I have turned the toggle off that displays unique nodes only. This means that if someone visits the page, clicks away from the site (eg on the link for covid exemptions) and then comes back to the page, they are shown only once.

If someone viewed the [Being Human visual story](https://wellcomecollection.org/pages/Xeo6OREAAB8A3wTA), went to another page and then returned to the visual story, because this is a backwards path exploration, the second view of the visual story would be the end point. The previous view of the visual story would appear among the numbers somewhere to the left of the end point. In fact, you can see 4 people did just that.
