### ISSUE TITLE
Review how licence, attribution and copyright information is constructed and displayed

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9963]
# What?

Review and make improvements to the way we construct and display licence, credit/attribution and copyright information on works and item pages.

We need to rationalise how we display:
- Licence (from IIIF manifest)
- [Human-readable licence explainer](https://docs.google.com/spreadsheets/d/1IKHmOE_zX6Qi0M_Ys5QMx7QKSJfk31OB9a13a0TF-Yg/edit?usp=sharing) from codebase
- Credit line (constructed from IIIF manifest)
- Copyright note (from Sierra) considering digitised and non-digitised material

# Why? 

Back in 2017 when we began generating credit lines for digitised items, we hadn't yet entered into the world of having digitised material for which we did not have open licenses like CC and PDM. In that scenario, we always wanted to have an attribution/credit line that followed the TASL format because that's what was recommended for Creative Commons licenced material.

Now we're getting more born digital material that is in copyright and has a different set of needs around crediting the authors. Our old model isn't working in this new world.

# Background  
https://wiki.creativecommons.org/wiki/best_practices_for_attribution

https://wellcome.slack.com/archives/C8X9YKM5X/p1686925927988869

# Done when
-  [x] Current mapping documented for shared understanding
-  [x] Consult Collections Info for recommendations for citing in copyright material
- [ ] Recommendations for next steps (which may include redesign on works/item pages, new data fields in Goobi)

**Comment by jennpb** [comment]
Examples as discussed with @rcantin-w 

https://wellcomecollection.org/works/y2mtrewc - WORKING EXAMPLE
This is working as expected
- Public Domain licence
- Human readable licence text
- Credit line to attribute digitised item to WC

https://wellcomecollection.org/works/yp5qrpvk - CREDIT LINE PROBLEM
This is not working as expected. It's one of our 3rd party digitised books, originally from The University of Leeds Library.
- In copyright
- No human readable licence text (we don't have any)
- Credit line is borked - what's happening here? 
- - Phrases merged into one
- - Text is linked but no URL provided

https://wellcomecollection.org/works/um8agcr7/items - Another credit line problem shown in viewer

https://wellcomecollection.org/works/b373tjqs - NOT DIGITISED, HAS A COPYRIGHT NOTE
This is working as currently expected.

https://wellcomecollection.org/works/wys2bdym - In copyright example; 'Can this be used?' component hidden #9968

**Comment by rcantin-w** [comment]
# Licence section

This whole section only gets rendered **if** the work has a Digital Location Licence.

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/8d98cb60-233a-47fc-9ea0-cbbf3d9e8872)


## Licence

Taken from the Digital Location License label.


## Access conditions (to be revised)

I couldn't find any example where this was rendered, but if the Digital Location has Access Conditions Terms, they get rendered at this stage.


## Can I use this?
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/f2a345e4-48d9-4a8e-a7e5-73f855fde32e)

### First section
The first section is based off the Digital Location's license's "human readable text". If it exists, it gets displayed. I'm unsure how it is structured within the system itself, but in the code it comes back as an array, with a paragraph per child. In [this screenshotted example](https://wellcomecollection.org/works/y2mtrewc) : 

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/47c86935-56e5-482e-9d8d-c5938598c921)


### Second section ("Credit")
1. **Credit:** (hard-coded) 2. **Work title**. 3. (If there is either a Digital Location credit OR a "IIIF Credit" which is coming from the "Attribution and usage" metadata in IIIF) **it displays as link to the Work**. 4. **Digital Location License Label** (if there is a digital location license url, it displays as a link, otherwise it's just text)

So in [this screenshotted example](https://wellcomecollection.org/works/yp5qrpvk).


![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/b6f05466-5291-47fe-8a27-15b61effb497)




**1.** Credit: **2.** Reasons, rules, and recipes for using the Cow and Gate Milk Powder, with a few suggestive menus for flesh-eaters and non-flesh-eaters, and an introduction / by a practical housekeeper ; revised by Eustace Miles. **3.** [This material has been provided by This material has been provided by The University of Leeds Library. The original may be consulted at The University of Leeds Library. where the originals may be consulted.](https://wellcomecollection.org/works/yp5qrpvk). **4.** [In copyright](http://rightsstatements.org/vocab/InC/1.0/)

**Comment by jennpb** [comment]
Meeting with Alexandra on 4/7 to get some peer feedback/subject expertise.

**Comment by rcantin-w** [comment]
Moved to Blocked since we won't be moving on this until then - let me know if I can help on that meeting!

**Comment by jennpb** [comment]
@rcantin-w 

> This whole section only gets rendered if the work has a Digital Location Licence

Where is the Digital Location Licence found?

**Comment by rcantin-w** [comment]
> Where is the Digital Location Licence found?
It's from the IIIF manifest, which I think can be either a Presentation or an Image. If more details are needed I might call on @gestchild as this is where my knowledge stops!
