### ISSUE TITLE
Discovery: Add links to useful guides in Exhibition pages (design)

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9978]
We would like to find out how useful it would be to use a component similar to what we have in exhibition guides, but on Exhibition pages themselves. This could facilitate finding the relevant content for our users and make our offer more obvious. Links to exhibition guides and other exhibition-specific content are currently a link in the body text.

![Image](https://user-images.githubusercontent.com/110461050/247901972-37755b86-62b0-4653-801d-0b450b1b3227.png)

This was an idea Jenn had, first step would be to discuss with Dom and/or try it under a toggle.

Devs need to also think about how these could be linked. Is it a new field in Prismic? Is there a way to link the contents together and make it dynamic?

# Background
[JPB] We have a family of content formats that support an exhibition: exhibition guides and the content formats contained within; PDF sensory maps; other related content as expressed like this:
https://miro.com/app/board/uXjVME3nANE=/

<img width="421" alt="Screenshot 2023-06-22 at 13 41 54" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/1446139/e6ebde59-04a1-4888-881e-5816c3cc0ce6">

These are currently treated as links in body text, but there's no visual hierarchy or way to call each of these content items as a useful thematic grouping. These content formats are unlikely to have featured images that can be reappropriated for a card, but they still would benefit from having a more dominant presence on the page. We already have the idea of a solid colour card/link style, as currently used in the exhibition guides. Can we design something that has a logical rationale and consistent usage? How might we reuse what we already have?

The aims are to 
- make the related content more visible in the context of an exhibition page
- create a useful visual hierarchy on an exhibition page
- enable a dynamic relationship between an exhibition and the related content

**Comment by DominiqueMarshall** [comment]
I've been exploring several card variations that would be beneficial in helping to establish more of a hierarchy with the access content within an exhibition page):


**Version 1 (minimal/default styling option)**: https://zpl.io/KGW3r4E
The idea behind these "cards" is to help establish the different forms of repeatable WC access content as important/helpful resources to click on. Any extra publications that may be created would stay as text links as shown in the mockup.

The digital exhibition guide and the visual story cards have arrows as a subtle indication that there's an onward journey to a new webpage. As those pages don't have a featured image, these cards don't either.

The sensory map and visual story pdf cards are slightly different in that they **do** images (the front cover of the pdfs), have a download icon. Ideally the whole card would be clickable rather than just the text in each card.


**Version 2 - adding colour**: https://zpl.io/mDqmQ16
Building on version 1, I tried using colour in a more subtle way than currently used in the digital exhibition guides. 


**Version 3**: https://zpl.io/8lx3ryK
Same as version 2, but with a section background to differentiate the access content even more.


@rcantin-w @davidpmccormick Starting with Version 1, I'd like to find out how feasible it would be to have a new card style like this in Prismic specifically for access content, and whether you foresee any major tech issues/constraints (I imagine the two colour layout will be one?)
